\documentclass[color=usenames,dvipsnames]{beamer}\usepackage[]{graphicx}\usepackage[]{xcolor}
% maxwidth is the original width if it is less than linewidth
% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0, 0, 0}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.69,0.494,0}{#1}}%
\newcommand{\hlsng}[1]{\textcolor[rgb]{0.749,0.012,0.012}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.514,0.506,0.514}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hldef}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0,0,0}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0,0.341,0.682}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0,0,0}{\textbf{#1}}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.004,0.004,0.506}{#1}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\let\hlstd\hldef
\let\hlstr\hlsng
\usepackage{alltt}
%\documentclass[color=usenames,dvipsnames,handout]{beamer}

\usepackage[roman]{../lectures}
%\usepackage[sans]{../lectures}


\hypersetup{pdfpagemode=UseNone,pdfstartview={FitV}}

\mode<handout>{
  \usetheme{default}
%  \setbeamercolor{background canvas}{bg=black!5}
% \pgfpagesuselayout{4 on 1}[letterpaper,landscape,border shrink=2.5mm]
%  \pgfpagesuselayout{2 on 1}[letterpaper,border shrink=10mm]
}


% Load function to compile and open PDF


% Compile and open PDF






% New command for inline code that isn't to be evaluated
\definecolor{inlinecolor}{rgb}{0.878, 0.918, 0.933}
\newcommand{\inr}[1]{\colorbox{inlinecolor}{\texttt{#1}}}
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}




\begin{frame}[plain]
  \LARGE
  \centering
  {
    \huge Hierarchical distance sampling: \\
    \LARGE simulation, fitting, and prediction %, and random effects \\
  }
  {\color{default} \rule{\textwidth}{0.1pt} }
  \vfill
  \large
  WILD(FISH) 8390 \\
%   Estimation of Fish and Wildlife Population Parameters \\
  Inference for Models of Fish and Wildlife Population Dynamics \\
  \vfill
  \large
  Richard Chandler \\
  University of Georgia \\
\end{frame}






\section{Overview}



\begin{frame}[plain]
  \frametitle{Outline}
  \Large
  \only<1>{\tableofcontents}%[hideallsubsections]}
  \only<2 | handout:0>{\tableofcontents[currentsection]}%,hideallsubsections]}
\end{frame}



\begin{frame}
  \frametitle{Distance sampling overview}
  Distance sampling is one of the oldest wildlife sampling methods. \\
  \pause
  \vfill
  It's based on the simple idea that detection probability should
  decline with distance between an animal and a transect. \\
  \pause
  \vfill
  If we can estimate the function describing how $p$ declines with
  distance $x$, we can estimate abundance\dots if certain
  assumptions hold, as always. \\
\end{frame}



\begin{frame}
  \frametitle{Distance sampling overview}
  The simplest estimator of abundance is 
  \[
    \hat{N} = \frac{n}{\hat{p}}
  \]
  where $n$ is the number of individuals detected, $p$ is detection
  probability, and $E(n)=Np$. \\
  \pause
  \vfill
  In distance sampling, detection probability is a \alert{function} of
  distance, rather than a constant, such that all individuals have
  unique detection probabilities. \\
  \pause
  \vfill
  As a result, we have to replace
  $p$ with \alert{average} detection probability:
  \[
    \hat{N} = \frac{n}{\hat{\bar{p}}}
  \]
  \pause
  \vfill
  How do we compute average detection probability ($\bar{p}$)?
\end{frame}



\begin{frame}
  \frametitle{Detection functions}
  To estimate average detection probability ($\bar{p}$), we need:
  \begin{itemize}
    \item A detection function $g(x)$ describing how $p$ declines with
      distance.
    \item A probability distribution $p(x)$ describing the
      distances of all animals (detected and not detected). 
  \end{itemize}
  \pause
  \vfill
  \centering
  The most common detection functions are: \\
  \vspace{6pt}
  \begin{tabular}{lc}
%    \centering
    \hline
    Detection function & $g(x)$ \\
    \hline
    Half normal & $\exp(-x^2 / (2\sigma^2))$ \\
    Negative exponential & $\exp(-x/\sigma)$ \\
    Hazard rate & $1-\exp(-(x/a)^{-b})$ \\
    \hline
  \end{tabular}
\end{frame}


\begin{frame}[fragile]
  \frametitle{Half-normal}
  \footnotesize
  \[
    g(x,\sigma) = \exp(-x^2/(2\sigma^2))
  \]
  \vspace{-12pt}
  \centering
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{sigma1} \hlkwb{<-} \hlnum{25}\hldef{; sigma2} \hlkwb{<-} \hlnum{50}
\hlkwd{plot}\hldef{(}\hlkwa{function}\hldef{(}\hlkwc{x}\hldef{)} \hlkwd{exp}\hldef{(}\hlopt{-}\hldef{x}\hlopt{^}\hlnum{2}\hlopt{/}\hldef{(}\hlnum{2}\hlopt{*}\hldef{sigma1}\hlopt{^}\hlnum{2}\hldef{)),} \hlkwc{from}\hldef{=}\hlnum{0}\hldef{,} \hlkwc{to}\hldef{=}\hlnum{100}\hldef{,}
     \hlkwc{xlab}\hldef{=}\hlsng{"Distance (x)"}\hldef{,} \hlkwc{ylab}\hldef{=}\hlsng{"Detection probability (p)"}\hldef{)}
\hlkwd{plot}\hldef{(}\hlkwa{function}\hldef{(}\hlkwc{x}\hldef{)} \hlkwd{exp}\hldef{(}\hlopt{-}\hldef{x}\hlopt{^}\hlnum{2}\hlopt{/}\hldef{(}\hlnum{2}\hlopt{*}\hldef{sigma2}\hlopt{^}\hlnum{2}\hldef{)),} \hlkwc{from}\hldef{=}\hlnum{0}\hldef{,} \hlkwc{to}\hldef{=}\hlnum{100}\hldef{,} \hlkwc{add}\hldef{=}\hlnum{TRUE}\hldef{,} \hlkwc{col}\hldef{=}\hlnum{4}\hldef{)}
\hlkwd{legend}\hldef{(}\hlnum{70}\hldef{,} \hlnum{1}\hldef{,} \hlkwd{c}\hldef{(}\hlsng{"sigma=25"}\hldef{,} \hlsng{"sigma=50"}\hldef{),} \hlkwc{lty}\hldef{=}\hlnum{1}\hldef{,} \hlkwc{col}\hldef{=}\hlkwd{c}\hldef{(}\hlsng{"black"}\hldef{,}\hlsng{"blue"}\hldef{))}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=0.7\linewidth]{figure/hn-1} 

}


\end{knitrout}
\end{frame}




\begin{frame}[fragile]
  \frametitle{Negative exponential}
  \footnotesize
  \[
    g(x,\sigma) = \exp(-x/\sigma)
  \]
  \vspace{-12pt}
  \centering
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{sigma1} \hlkwb{<-} \hlnum{25}\hldef{; sigma2} \hlkwb{<-} \hlnum{50}
\hlkwd{plot}\hldef{(}\hlkwa{function}\hldef{(}\hlkwc{x}\hldef{)} \hlkwd{exp}\hldef{(}\hlopt{-}\hldef{x}\hlopt{/}\hldef{sigma1),} \hlkwc{from}\hldef{=}\hlnum{0}\hldef{,} \hlkwc{to}\hldef{=}\hlnum{100}\hldef{,}
     \hlkwc{xlab}\hldef{=}\hlsng{"Distance (x)"}\hldef{,} \hlkwc{ylab}\hldef{=}\hlsng{"Detection probability (p)"}\hldef{)}
\hlkwd{plot}\hldef{(}\hlkwa{function}\hldef{(}\hlkwc{x}\hldef{)} \hlkwd{exp}\hldef{(}\hlopt{-}\hldef{x}\hlopt{/}\hldef{sigma2),} \hlkwc{from}\hldef{=}\hlnum{0}\hldef{,} \hlkwc{to}\hldef{=}\hlnum{100}\hldef{,} \hlkwc{add}\hldef{=}\hlnum{TRUE}\hldef{,} \hlkwc{col}\hldef{=}\hlnum{4}\hldef{)}
\hlkwd{legend}\hldef{(}\hlnum{70}\hldef{,} \hlnum{1}\hldef{,} \hlkwd{c}\hldef{(}\hlsng{"sigma=25"}\hldef{,} \hlsng{"sigma=50"}\hldef{),} \hlkwc{lty}\hldef{=}\hlnum{1}\hldef{,} \hlkwc{col}\hldef{=}\hlkwd{c}\hldef{(}\hlsng{"black"}\hldef{,}\hlsng{"blue"}\hldef{))}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=0.7\linewidth]{figure/nexp-1} 

}


\end{knitrout}
\end{frame}





\begin{frame}[fragile]
  \frametitle{Hazard rate}
  \footnotesize
  \[
    g(x,a,b) = 1-\exp(-(x/a)^{-b})
  \]
  \vspace{-12pt}
  \centering
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{a1} \hlkwb{<-} \hlnum{25}\hldef{; a2} \hlkwb{<-} \hlnum{50}\hldef{; b1} \hlkwb{<-} \hlnum{2}\hldef{; b2} \hlkwb{<-} \hlnum{10}
\hlkwd{plot}\hldef{(}\hlkwa{function}\hldef{(}\hlkwc{x}\hldef{)} \hlnum{1}\hlopt{-}\hlkwd{exp}\hldef{(}\hlopt{-}\hldef{(x}\hlopt{/}\hldef{a1)}\hlopt{^}\hldef{(}\hlopt{-}\hldef{b1)),} \hlkwc{from}\hldef{=}\hlnum{0}\hldef{,} \hlkwc{to}\hldef{=}\hlnum{100}\hldef{,}
     \hlkwc{xlab}\hldef{=}\hlsng{"Distance (x)"}\hldef{,} \hlkwc{ylab}\hldef{=}\hlsng{"Detection probability (p)"}\hldef{,} \hlkwc{ylim}\hldef{=}\hlnum{0}\hlopt{:}\hlnum{1}\hldef{)}
\hlkwd{plot}\hldef{(}\hlkwa{function}\hldef{(}\hlkwc{x}\hldef{)} \hlnum{1}\hlopt{-}\hlkwd{exp}\hldef{(}\hlopt{-}\hldef{(x}\hlopt{/}\hldef{a2)}\hlopt{^}\hldef{(}\hlopt{-}\hldef{b2)),} \hlkwc{from}\hldef{=}\hlnum{0}\hldef{,} \hlkwc{to}\hldef{=}\hlnum{100}\hldef{,} \hlkwc{add}\hldef{=}\hlnum{TRUE}\hldef{,} \hlkwc{col}\hldef{=}\hlnum{4}\hldef{)}
\hlkwd{legend}\hldef{(}\hlnum{70}\hldef{,} \hlnum{1}\hldef{,} \hlkwd{c}\hldef{(}\hlsng{"a=25, b=2"}\hldef{,} \hlsng{"a=50, b=10"}\hldef{),} \hlkwc{lty}\hldef{=}\hlnum{1}\hldef{,} \hlkwc{col}\hldef{=}\hlkwd{c}\hldef{(}\hlsng{"black"}\hldef{,}\hlsng{"blue"}\hldef{))}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=0.7\linewidth]{figure/haz-1} 

}


\end{knitrout}
\end{frame}



\begin{frame}
  \frametitle{Average detection probability ($\bar{p}$)}
  Regardless of the chosen detection function, average detection
  probability is defined as: 
  \[
%     \bar{p} = \int g(x)p(x) \; \mathrm{d}x
%     \bar{p} = \int_{b_1}^{b_2} g(x)p(x) \; \mathrm{d}x
     \bar{p} = \int_{0}^{B} g(x)p(x) \; \mathrm{d}x
   \]
%   where $b_1$ and $b_2$ are the limits of the distance interval.
   where $B$ is the width of the transect.
  \pause
  \vfill
  All that remains is the specification of $p(x)$, the
  distribution of distances (between animals and the transect).
  \pause
  \vfill
  To understand why $p(x)$ is needed, think about it this way:
  \begin{itemize}
    \item If most animals are close to the transect, $\bar{p}$ would
      be high
    \item If most animals are far from the transect, $\bar{p}$ would
      be low
  \end{itemize}
  % \pause
  % \vfill
  % The standard assumption (for line transects) is that animals are
  % uniformly distributed with respect to the transect
\end{frame}



\begin{frame}
  \frametitle{What should we use for $p(x)$?}
  What distribution should we use for the distances between animals
  and transects?
  \pause
  \vfill
  In \alert{line-transect sampling}, it is often assumed that animals
  are uniformly distributed with respect to the transect.
  \begin{itemize}
    \item Consequently, $p(x) = 1/B$, where $x$ is the
      \alert{perpendicular} distance between animal and transect
    \item This is guaranteed by random transect placement
    \item Can also be justified if animals are neither attracted to
      the transects or avoid them. 
  \end{itemize}
  \pause
  \vfill
  In \alert{point-transect sampling}, we make the same assumptions,
  but we recognize that area increases with distance from a point.
  \begin{itemize}
    \item Consequently, $p(x) = 2x/B^2$ (see pg. 408 in AHM)
    \item Here, $x$ is the \alert{radial} distance to an animal
  \end{itemize}
\end{frame}




\begin{frame}[fragile]
  \frametitle{Computing $\bar{p}$ for line transects}
  Half-normal detection function and line-transect sampling.
  \vspace{-6pt}
\begin{knitrout}\footnotesize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{B} \hlkwb{<-} \hlnum{100}                                         \hlcom{# Transect width}
\hldef{g} \hlkwb{<-} \hlkwa{function}\hldef{(}\hlkwc{x}\hldef{,} \hlkwc{sigma}\hldef{=}\hlnum{25}\hldef{)} \hlkwd{exp}\hldef{(}\hlopt{-}\hldef{x}\hlopt{^}\hlnum{2}\hlopt{/}\hldef{(}\hlnum{2}\hlopt{*}\hldef{sigma}\hlopt{^}\hlnum{2}\hldef{))} \hlcom{# g(x)}
\hldef{pdf} \hlkwb{<-} \hlkwa{function}\hldef{(}\hlkwc{x}\hldef{)} \hlnum{1}\hlopt{/}\hldef{B}                           \hlcom{# p(x), constant}
\end{alltt}
\end{kframe}
\end{knitrout}
\pause
\vfill
  Do the integration
  \vspace{-6pt}
\begin{knitrout}\footnotesize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{gp} \hlkwb{<-} \hlkwa{function}\hldef{(}\hlkwc{x}\hldef{)} \hlkwd{g}\hldef{(x)}\hlopt{*}\hlkwd{pdf}\hldef{(x)}
\hldef{(pbar} \hlkwb{<-} \hlkwd{integrate}\hldef{(gp,} \hlkwc{lower}\hldef{=}\hlnum{0}\hldef{,} \hlkwc{upper}\hldef{=B)}\hlopt{$}\hldef{value)}
\end{alltt}
\begin{verbatim}
## [1] 0.3133087
\end{verbatim}
\end{kframe}
\end{knitrout}
% \pause
% \vfill
%   Note the equivalence
%   \vspace{-6pt}
% <<pbar-hn-int2,size='footnotesize'>>=
% (pbar <- integrate(g, lower=0, upper=B)$value / B)
% (pbar <- (pnorm(B,0,25) - pnorm(0,0,25)) / dnorm(0,0,25) / B)
% @
\pause
\vfill
\centering
31.3\% chance of detecting an individual within 100 m. \\
\end{frame}



\begin{frame}[fragile]
  \frametitle{Computing $\bar{p}$ for point transects}
  Half-normal detection function and point-transect sampling.
  \vspace{-6pt}
\begin{knitrout}\footnotesize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{B} \hlkwb{<-} \hlnum{100}                                         \hlcom{# Transect width}
\hldef{g} \hlkwb{<-} \hlkwa{function}\hldef{(}\hlkwc{x}\hldef{,} \hlkwc{sigma}\hldef{=}\hlnum{25}\hldef{)} \hlkwd{exp}\hldef{(}\hlopt{-}\hldef{x}\hlopt{^}\hlnum{2}\hlopt{/}\hldef{(}\hlnum{2}\hlopt{*}\hldef{sigma}\hlopt{^}\hlnum{2}\hldef{))} \hlcom{# g(x)}
\hldef{pdf} \hlkwb{<-} \hlkwa{function}\hldef{(}\hlkwc{x}\hldef{)} \hlnum{2}\hlopt{*}\hldef{x}\hlopt{/}\hldef{B}\hlopt{^}\hlnum{2}                       \hlcom{# p(x)}
\end{alltt}
\end{kframe}
\end{knitrout}
\pause
\vfill
  Do the integration
  \vspace{-6pt}
\begin{knitrout}\footnotesize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{gp} \hlkwb{<-} \hlkwa{function}\hldef{(}\hlkwc{x}\hldef{)} \hlkwd{g}\hldef{(x)}\hlopt{*}\hlkwd{pdf}\hldef{(x)}
\hldef{(pbar} \hlkwb{<-} \hlkwd{integrate}\hldef{(gp,} \hlkwc{lower}\hldef{=}\hlnum{0}\hldef{,} \hlkwc{upper}\hldef{=B)}\hlopt{$}\hldef{value)}
\end{alltt}
\begin{verbatim}
## [1] 0.1249581
\end{verbatim}
\end{kframe}
\end{knitrout}
\pause
\vfill
%   Note the equivalence
%   \vspace{-6pt}
% <<pbar-hn-int2-pt,size='footnotesize'>>=
% sigma <- 25
% (pbar <- (sigma^2*(1-exp(-B^2/(2*sigma^2))) -
%           sigma^2*(1-exp(-0^2/(2*sigma^2)))) * 2*pi/(pi*B^2))
% @
% \pause
% \vfill
\centering
12.5\% chance of detecting an individual within 100 m. \\
\end{frame}





\begin{frame}
  \frametitle{Shiny App}
  % Building off the previous example\dots
  % \begin{enumerate}
  %   \item Use R code and the Shiny app below to compute $\bar{p}$ for line-transect sampling when 
  %     $\sigma=50, 100, \mathrm{and}\, 200$, instead of $\sigma=25$.  
  %   \item Repeat, but for point-transect sampling. 
  %   \end{enumerate}
  %   \vfill
    \centering
    \href{
      https://richard-chandler.shinyapps.io/distance-sampling/
    }{
      \Large
%      Shiny App \\
      \normalsize
      \color{blue}
      https://richard-chandler.shinyapps.io/distance-sampling/
    }
\end{frame}




\begin{frame}
  \frametitle{\large Conventional vs hierarchical distance sampling}
  \alert{Conventional} distance sampling
  \begin{itemize}
    \item Focus is on estimation of detection function parameters and density
    \item No model for spatial variation in density
    \item Data are individual-level distances
    \item We'll deal with CDS in more depth as a prelude to
      spatial-capture recapture
  \end{itemize}
  \pause
  \vfill
  \alert{Hierarchical} distance sampling
  \begin{itemize}
    \item Focus is on estimation of detection function parameters and
      spatial variation in abundance/density
    \item Data are counts of individuals in each distance bin
    \item Multinomial $N$-mixture model with a unique function for
      computing the multinomial cell probabilities 
  \end{itemize}
\end{frame}




\begin{frame}
  \frametitle{Hierarchical distance sampling}
  \small
  State model (with Poisson assumption)
  \begin{gather*}
    \mathrm{log}(\lambda_i) = \beta_0 + \beta_1 {w_{i1}} +
    \beta_2 {w_{i2}} + \cdots \\
    N_i \sim \mathrm{Poisson}(\lambda_i)
  \end{gather*}
  \pause
  Observation model
  \begin{gather*}
    \mathrm{log}(\sigma_{i}) = \alpha_0 + \alpha_1 {w_{i1}}
    + \alpha_2 {w_{i3}} + \cdots \\
    \{y_{i1}, \dots, y_{iK}\}  \sim \mathrm{Multinomial}(N_i,
%    \pi(b_1, \dots, b_{J+1}, x, \sigma_i))
    \pi(x, \sigma_i))
  \end{gather*}
  \pause
  \small
  Definitions \\
  $\lambda_i$ -- Expected value of abundance at site $i$ \\
  $N_i$ -- Realized value of abundance at site $i$ \\
  $\sigma_{i}$ -- Scale parameter of detection function $g(x)$ at site $i$ \\
  $\pi(x,\sigma_i)$ -- Function computing multinomial cell probs \\
  $y_{ij}$ -- count for distance bin $j$ (final count is unobserved) \\
  $w_1$, $w_2$, $w_3$ -- site covariates %\hfill %\\
\end{frame}






\section{Point transects}

\subsection{Simulation}


\begin{frame}
  \frametitle{Outline}
  \Large
  \tableofcontents[currentsection,currentsubsection]
\end{frame}



\begin{frame}
  \frametitle{Multinomial cell probs for point transects}
  \small
  Definitions needed for computing \alert{bin-specific} $\bar{p}$ and
  multinomial cell probabilities. 
  \begin{itemize}
    \small
    \setlength\itemsep{1pt}
    \item $y_{ij}$ -- number of individuals detected at site $i$ in bin $j$
    \item $\sigma_i$ -- scale parameter of detection function $g(x)$
    \item $b_1, \dots, b_J$ -- Distance break points defining $J$
      distance intervals
    % \item $a_1, \dots, a_J$ -- Area of annulus $j$
    % \item $\bar{p}_j = \int_{b_j}^{b_{j+1}} g(x,\sigma)p(x|b_j\le x<b_{j+1})\, \mathrm{d}x$
    % \item $p(x|b_j\le x<b_{j+1}) = 2\pi x/a_j$
    % \item $\psi_j=\Pr(b_j\le x<b_{j+1})=a_j/(\pi B^2)$
    \item $\bar{p}_j$ -- Average detection probability in distance interval $j$.
    \item $\psi_j$ -- Probability of occuring in distance band $j$
  \end{itemize}
  \pause \vfill
  \footnotesize
  \begin{columns}
    \column{0.9\paperwidth}
    \begin{tabular}{lc}
      \hline
      \centering
      Description                       & Multinomial cell probability \\
      \hline
      Pr(occurs and detected in first distance bin)  & $\pi_1 = \psi_1\bar{p}_1$   \\
      Pr(occurs and detected in second distance bin)  & $\pi_2 = \psi_2\bar{p}_2$   \\
      {\centering $\cdots$}             & $\cdots$                     \\
      Pr(occurs and detected in last distance bin)  & $\pi_J = \psi_J\bar{p}_J$   \\
      Pr(not detected)                  & $\pi_{K} = 1-\sum_{j=1}^J \pi_j$          \\
      \hline
    \end{tabular}
  \end{columns}
\end{frame}





\begin{frame}[fragile]
  \frametitle{Point transects, no covariates}
  \small
  Abundance
  \vspace{-6pt}
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{B} \hlkwb{<-} \hlnum{100}\hldef{; Area} \hlkwb{<-} \hldef{pi}\hlopt{*}\hldef{B}\hlopt{^}\hlnum{2}\hlopt{/}\hlnum{1e4}   \hlcom{## plot radius (B) and area in ha}
\hldef{nSites} \hlkwb{<-} \hlnum{100}\hldef{; lambda1} \hlkwb{<-} \hlnum{0.9}  \hlcom{## Expected value of density}
\hldef{N3} \hlkwb{<-} \hlkwd{rpois}\hldef{(}\hlkwc{n}\hldef{=nSites,} \hlkwc{lambda}\hldef{=lambda1}\hlopt{*}\hldef{Area)}
\end{alltt}
\end{kframe}
\end{knitrout}
  \pause
  \vfill
  Multinomial cell probabilities
  \vspace{-6pt}
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{J} \hlkwb{<-} \hlnum{5}                     \hlcom{# distance bins}
\hldef{sigma} \hlkwb{<-} \hlnum{50}                \hlcom{# scale parameter}
\hldef{b} \hlkwb{<-} \hlkwd{seq}\hldef{(}\hlnum{0}\hldef{, B,} \hlkwc{length}\hldef{=J}\hlopt{+}\hlnum{1}\hldef{)} \hlcom{# distance break points}
\hldef{area} \hlkwb{<-} \hldef{pi}\hlopt{*}\hldef{b}\hlopt{^}\hlnum{2}             \hlcom{# area of each circle}
\hldef{psi} \hlkwb{<-} \hldef{(area[}\hlopt{-}\hlnum{1}\hldef{]}\hlopt{-}\hldef{area[}\hlopt{-}\hldef{(J}\hlopt{+}\hlnum{1}\hldef{)])} \hlopt{/} \hldef{area[J}\hlopt{+}\hlnum{1}\hldef{]}
\hldef{pbar3} \hlkwb{<-} \hlkwd{numeric}\hldef{(J)}        \hlcom{# average detection probability}
\hldef{pi3} \hlkwb{<-} \hlkwd{numeric}\hldef{(J}\hlopt{+}\hlnum{1}\hldef{)}        \hlcom{# multinomial cell probs}
\hlkwa{for}\hldef{(j} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{J) \{}
    \hldef{pbar3[j]} \hlkwb{<-} \hlkwd{integrate}\hldef{(}\hlkwa{function}\hldef{(}\hlkwc{x}\hldef{)} \hlkwd{exp}\hldef{(}\hlopt{-}\hldef{x}\hlopt{^}\hlnum{2}\hlopt{/}\hldef{(}\hlnum{2}\hlopt{*}\hldef{sigma}\hlopt{^}\hlnum{2}\hldef{))}\hlopt{*}\hldef{x,}
                          \hlkwc{lower}\hldef{=b[j],} \hlkwc{upper}\hldef{=b[j}\hlopt{+}\hlnum{1}\hldef{])}\hlopt{$}\hldef{value} \hlopt{*}
                          \hldef{(}\hlnum{2}\hlopt{*}\hldef{pi}\hlopt{/}\hlkwd{diff}\hldef{(area)[j])}
    \hldef{pi3[j]} \hlkwb{<-} \hldef{pbar3[j]}\hlopt{*}\hldef{psi[j] \}; pi3[J}\hlopt{+}\hlnum{1}\hldef{]} \hlkwb{<-} \hlnum{1}\hlopt{-}\hlkwd{sum}\hldef{(pi3[}\hlnum{1}\hlopt{:}\hldef{J])}
\end{alltt}
\end{kframe}
\end{knitrout}
  \pause
  \vfill
  Detections in each distance interval
  \vspace{-6pt}
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{y3.all} \hlkwb{<-} \hlkwd{matrix}\hldef{(}\hlnum{NA}\hldef{,} \hlkwc{nrow}\hldef{=nSites,} \hlkwc{ncol}\hldef{=J}\hlopt{+}\hlnum{1}\hldef{)}
\hlkwa{for}\hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{nSites) \{}
    \hldef{y3.all[i,]} \hlkwb{<-} \hlkwd{rmultinom}\hldef{(}\hlkwc{n}\hldef{=}\hlnum{1}\hldef{,} \hlkwc{size}\hldef{=N3[i],} \hlkwc{prob}\hldef{=pi3)    \}}
\hldef{y3} \hlkwb{<-} \hldef{y3.all[,}\hlnum{1}\hlopt{:}\hldef{J]}  \hlcom{## Drop final cell}
\end{alltt}
\end{kframe}
\end{knitrout}
\end{frame}



\begin{frame}[fragile]
  \frametitle{Observed distances}
  \centering
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{plot}\hldef{(b[}\hlopt{-}\hldef{(J}\hlopt{+}\hlnum{1}\hldef{)]}\hlopt{+}\hlnum{10}\hldef{,} \hlkwd{colSums}\hldef{(y3),} \hlkwc{type}\hldef{=}\hlsng{"h"}\hldef{,} \hlkwc{lwd}\hldef{=}\hlnum{80}\hldef{,} \hlkwc{lend}\hldef{=}\hlnum{2}\hldef{,} \hlkwc{col}\hldef{=}\hlsng{"skyblue4"}\hldef{,}
     \hlkwc{xlim}\hldef{=}\hlkwd{c}\hldef{(}\hlnum{0}\hldef{,}\hlnum{100}\hldef{),} \hlkwc{ylim}\hldef{=}\hlkwd{c}\hldef{(}\hlnum{0}\hldef{,} \hlnum{70}\hldef{),} \hlkwc{xlab}\hldef{=}\hlsng{"Distance"}\hldef{,} \hlkwc{ylab}\hldef{=}\hlsng{"Detections"}\hldef{)}
\end{alltt}
\end{kframe}
\includegraphics[width=0.9\linewidth]{figure/dist-hist3-1} 
\end{knitrout}
\end{frame}




\begin{frame}[fragile]
  \frametitle{Point transects, covariates}
  \small
  Abundance
  \vspace{-6pt}
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{elevation} \hlkwb{<-} \hlkwd{rnorm}\hldef{(nSites)}
\hldef{beta0} \hlkwb{<-} \hlnum{2}\hldef{; beta1} \hlkwb{<-} \hlnum{1}
\hldef{lambda4} \hlkwb{<-} \hlkwd{exp}\hldef{(beta0} \hlopt{+} \hldef{beta1}\hlopt{*}\hldef{elevation)}   \hlcom{# E(density)}
\hldef{N4} \hlkwb{<-} \hlkwd{rpois}\hldef{(}\hlkwc{n}\hldef{=nSites,} \hlkwc{lambda}\hldef{=lambda4}\hlopt{*}\hldef{Area)}
\end{alltt}
\end{kframe}
\end{knitrout}
  \pause
  \vfill
  Multinomial cell probabilities
  \vspace{-6pt}
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{noise} \hlkwb{<-} \hlkwd{rnorm}\hldef{(nSites)}
\hldef{alpha0} \hlkwb{<-} \hlnum{3}\hldef{; alpha1} \hlkwb{<-} \hlopt{-}\hlnum{0.5}
\hldef{sigma4} \hlkwb{<-} \hlkwd{exp}\hldef{(alpha0} \hlopt{+} \hldef{alpha1}\hlopt{*}\hldef{noise)}
\hldef{pi4} \hlkwb{<-} \hlkwd{matrix}\hldef{(}\hlnum{NA}\hldef{, nSites, J}\hlopt{+}\hlnum{1}\hldef{)} \hlcom{# multinomial cell probs}
\hlkwa{for}\hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{nSites) \{}
  \hlkwa{for}\hldef{(j} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{J) \{}
      \hldef{pi4[i,j]} \hlkwb{<-} \hlkwd{integrate}\hldef{(}\hlkwa{function}\hldef{(}\hlkwc{x}\hldef{)} \hlkwd{exp}\hldef{(}\hlopt{-}\hldef{x}\hlopt{^}\hlnum{2}\hlopt{/}\hldef{(}\hlnum{2}\hlopt{*}\hldef{sigma4[i]}\hlopt{^}\hlnum{2}\hldef{))}\hlopt{*}\hldef{x,}
          \hlkwc{lower}\hldef{=b[j],} \hlkwc{upper}\hldef{=b[j}\hlopt{+}\hlnum{1}\hldef{])}\hlopt{$}\hldef{value}\hlopt{*}\hldef{(}\hlnum{2}\hlopt{*}\hldef{pi}\hlopt{/}\hlkwd{diff}\hldef{(area)[j])}\hlopt{*}\hldef{psi[j] \}}
  \hldef{pi4[i,J}\hlopt{+}\hlnum{1}\hldef{]} \hlkwb{<-} \hlnum{1}\hlopt{-}\hlkwd{sum}\hldef{(pi4[i,}\hlnum{1}\hlopt{:}\hldef{J]) \}}
\end{alltt}
\end{kframe}
\end{knitrout}
  \pause
  \vfill
  Detections in each distance interval
  \vspace{-6pt}
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{y4.all} \hlkwb{<-} \hlkwd{matrix}\hldef{(}\hlnum{NA}\hldef{,} \hlkwc{nrow}\hldef{=nSites,} \hlkwc{ncol}\hldef{=J}\hlopt{+}\hlnum{1}\hldef{)}
\hlkwa{for}\hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{nSites) \{}
    \hldef{y4.all[i,]} \hlkwb{<-} \hlkwd{rmultinom}\hldef{(}\hlkwc{n}\hldef{=}\hlnum{1}\hldef{,} \hlkwc{size}\hldef{=N4[i],} \hlkwc{prob}\hldef{=pi4[i,])    \}}
\hldef{y4} \hlkwb{<-} \hldef{y4.all[,}\hlnum{1}\hlopt{:}\hldef{J]}
\end{alltt}
\end{kframe}
\end{knitrout}
\end{frame}






\begin{frame}[fragile]
  \frametitle{Simulated data}
  \begin{columns}
    \begin{column}{0.4\textwidth}
      \small
      Observations
%      \tiny
  \vspace{-6pt}
\begin{knitrout}\tiny
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{y4[}\hlnum{1}\hlopt{:}\hlnum{25}\hldef{,]}
\end{alltt}
\begin{verbatim}
##       [,1] [,2] [,3] [,4] [,5]
##  [1,]    0    0    0    0    0
##  [2,]    1    5    1    0    0
##  [3,]    0    0    0    0    0
##  [4,]    0    1    1    1    0
##  [5,]    1    0    0    0    0
##  [6,]    0    1    2    2    5
##  [7,]    0    0    1    0    0
##  [8,]    5    5    0    0    0
##  [9,]    4    2    2    0    0
## [10,]    1    1    0    0    0
## [11,]    2    0    1    0    0
## [12,]    0    0    0    0    0
## [13,]    3    0    0    0    0
## [14,]    2    1    0    0    0
## [15,]    0    1    0    0    1
## [16,]    2    0    0    0    0
## [17,]    0    0    0    0    0
## [18,]    1    1    0    0    0
## [19,]    0    1    0    0    0
## [20,]    1    2    0    0    0
## [21,]    1    0    3    2    2
## [22,]    0    0    0    0    0
## [23,]    0    1    0    0    0
## [24,]    0    0    0    0    0
## [25,]    0    0    0    0    0
\end{verbatim}
\end{kframe}
\end{knitrout}
  \end{column}
  \begin{column}{0.6\textwidth}
    \pause
%    \scriptsize
    {\centering Summary stats \\}
    \vspace{24pt}
    \small
    Proportion of sites known to be occupied
    \vspace{-6pt}
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{# Max count at each site}
\hldef{maxCounts} \hlkwb{<-} \hlkwd{apply}\hldef{(y4,} \hlnum{1}\hldef{, max)}
\hldef{naiveOccupancy} \hlkwb{<-} \hlkwd{sum}\hldef{(maxCounts}\hlopt{>}\hlnum{0}\hldef{)}\hlopt{/}\hldef{nSites}
\hldef{naiveOccupancy}
\end{alltt}
\begin{verbatim}
## [1] 0.77
\end{verbatim}
\end{kframe}
\end{knitrout}
  \pause
  \vfill
  \small
  Total detections in each distance interval
  \vspace{-6pt}
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{colSums}\hldef{(y4)}
\end{alltt}
\begin{verbatim}
## [1] 89 99 54 35 30
\end{verbatim}
\end{kframe}
\end{knitrout}
  \pause
  \vfill
  Naive abundance
  \vspace{-6pt}
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{sum}\hldef{(y4)}
\end{alltt}
\begin{verbatim}
## [1] 307
\end{verbatim}
\end{kframe}
\end{knitrout}
  \end{column}
  \end{columns}
\end{frame}






\subsection{Likelihood-based inference}




\begin{frame}[fragile]
  \frametitle{Prepare data in `unmarked'}
  \small
  Note the new arguments.
  \vspace{-6pt}
\begin{knitrout}\tiny
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{umf4} \hlkwb{<-} \hlkwd{unmarkedFrameDS}\hldef{(}\hlkwc{y}\hldef{=y4,} \hlkwc{siteCovs}\hldef{=}\hlkwd{data.frame}\hldef{(elevation,noise),} \hlkwc{dist.breaks}\hldef{=b,}
                       \hlkwc{survey}\hldef{=}\hlsng{"point"}\hldef{,} \hlkwc{unitsIn}\hldef{=}\hlsng{"m"}\hldef{)}
\end{alltt}
\end{kframe}
\end{knitrout}
\pause
\begin{knitrout}\tiny
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{summary}\hldef{(umf4)}
\end{alltt}
\begin{verbatim}
## unmarkedFrameDS Object
## 
## point-transect survey design
## Distance class cutpoints (m):  0 20 40 60 80 100 
## 
## 100 sites
## Maximum number of distance classes per site: 5 
## Mean number of distance classes per site: 5 
## Sites with at least one detection: 77 
## 
## Tabulation of y observations:
##   0   1   2   3   4   5   6   7   8   9  10 
## 351  85  31  13   6   5   2   2   1   2   2 
## 
## Site-level covariates:
##    elevation           noise         
##  Min.   :-2.2953   Min.   :-2.93845  
##  1st Qu.:-0.7225   1st Qu.:-0.72355  
##  Median :-0.2411   Median :-0.06353  
##  Mean   :-0.1119   Mean   :-0.05248  
##  3rd Qu.: 0.6033   3rd Qu.: 0.53973  
##  Max.   : 2.2662   Max.   : 2.47751
\end{verbatim}
\end{kframe}
\end{knitrout}
\end{frame}



\begin{frame}[fragile]
  \frametitle{Fit the model}
  \footnotesize
\begin{knitrout}\tiny
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{## fm4 <- distsamp(~noise ~elevation, umf4, keyfun="exp")     # negative exp}
\hlcom{## fm4 <- distsamp(~noise ~elevation, umf4, keyfun="hazard")  # hazard rate}
\hldef{fm4} \hlkwb{<-} \hlkwd{distsamp}\hldef{(}\hlopt{~}\hldef{noise} \hlopt{~}\hldef{elevation, umf4,} \hlkwc{keyfun}\hldef{=}\hlsng{"halfnorm"}\hldef{)}   \hlcom{# half-normal}
\hldef{fm4}
\end{alltt}
\begin{verbatim}
## 
## Call:
## distsamp(formula = ~noise ~ elevation, data = umf4, keyfun = "halfnorm")
## 
## Density (log-scale):
##             Estimate     SE    z   P(>|z|)
## (Intercept)    2.003 0.0904 22.2 7.87e-109
## elevation      0.945 0.0662 14.3  3.29e-46
## 
## Detection (log-scale):
##             Estimate     SE     z  P(>|z|)
## (Intercept)    2.963 0.0362  81.9 0.00e+00
## noise         -0.525 0.0288 -18.2 5.75e-74
## 
## AIC: 677.1907 
## Number of sites: 100
## 
## Survey design: point-transect
## Detection function: halfnorm
## UnitsIn: m
## UnitsOut: ha
\end{verbatim}
\end{kframe}
\end{knitrout}
% \pause
% \vfill
% Compare to actual parameter values:
% \vspace{-6pt}
% <<un-compare-pt,size='tiny'>>=
% c(beta0=beta0, beta1=beta1); c(alpha0=alpha0, alpha1=alpha1)
% @ 
\end{frame}





\begin{frame}[fragile]
  \frametitle{Prediction in `unmarked'}
  \small
  Create \texttt{data.frame} with prediction covariates. 
  \vspace{-6pt}
\begin{knitrout}\footnotesize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{pred.data} \hlkwb{<-} \hlkwd{data.frame}\hldef{(}\hlkwc{noise}\hldef{=}\hlkwd{seq}\hldef{(}\hlopt{-}\hlnum{3}\hldef{,} \hlnum{3}\hldef{,} \hlkwc{by}\hldef{=}\hlnum{0.5}\hldef{))}
\end{alltt}
\end{kframe}
\end{knitrout}
\pause
\vfill
Get predictions of $\sigma$ for each row of prediction data.
  \vspace{-6pt}
\begin{knitrout}\footnotesize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{sigma.pred} \hlkwb{<-} \hlkwd{predict}\hldef{(fm4,} \hlkwc{newdata}\hldef{=pred.data,}
                      \hlkwc{type}\hldef{=}\hlsng{'det'}\hldef{,} \hlkwc{append}\hldef{=}\hlnum{TRUE}\hldef{)}
\end{alltt}
\end{kframe}
\end{knitrout}
\pause
\vfill
  View $\sigma$ predictions
  \vspace{-6pt}
\begin{knitrout}\footnotesize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{print}\hldef{(}\hlkwd{head}\hldef{(sigma.pred),} \hlkwc{digits}\hldef{=}\hlnum{2}\hldef{)}
\end{alltt}
\begin{verbatim}
##   Predicted   SE lower upper noise
## 1        93 8.19    79   111  -3.0
## 2        72 5.37    62    83  -2.5
## 3        55 3.45    49    62  -2.0
## 4        43 2.18    38    47  -1.5
## 5        33 1.38    30    36  -1.0
## 6        25 0.92    23    27  -0.5
\end{verbatim}
\end{kframe}
\end{knitrout}
\end{frame}





\begin{frame}[fragile]
  \frametitle{Prediction in `unmarked'}
\begin{knitrout}\tiny
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{plot}\hldef{(Predicted} \hlopt{~} \hldef{noise, sigma.pred,} \hlkwc{ylab}\hldef{=}\hlsng{"Scale parameter (sigma)"}\hldef{,}
     \hlkwc{ylim}\hldef{=}\hlkwd{c}\hldef{(}\hlnum{0}\hldef{,}\hlnum{100}\hldef{),} \hlkwc{xlab}\hldef{=}\hlsng{"Noise level"}\hldef{,} \hlkwc{type}\hldef{=}\hlsng{"l"}\hldef{)}
\hlkwd{lines}\hldef{(lower} \hlopt{~} \hldef{noise, sigma.pred,} \hlkwc{col}\hldef{=}\hlsng{"grey"}\hldef{)}
\hlkwd{lines}\hldef{(upper} \hlopt{~} \hldef{noise, sigma.pred,} \hlkwc{col}\hldef{=}\hlsng{"grey"}\hldef{)}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=0.8\linewidth]{figure/pred-sigma-1} 

}


\end{knitrout}
\end{frame}





\begin{frame}[fragile]
  \frametitle{Prediction in `unmarked'}
\begin{knitrout}\tiny
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{plot}\hldef{(Predicted} \hlopt{~} \hldef{noise, sigma.pred,} \hlkwc{ylab}\hldef{=}\hlsng{"Scale parameter (sigma)"}\hldef{,}
     \hlkwc{ylim}\hldef{=}\hlkwd{c}\hldef{(}\hlnum{0}\hldef{,}\hlnum{100}\hldef{),} \hlkwc{xlab}\hldef{=}\hlsng{"Noise level"}\hldef{,} \hlkwc{type}\hldef{=}\hlsng{"l"}\hldef{)}
\hlkwd{lines}\hldef{(lower} \hlopt{~} \hldef{noise, sigma.pred,} \hlkwc{col}\hldef{=}\hlsng{"grey"}\hldef{)}
\hlkwd{lines}\hldef{(upper} \hlopt{~} \hldef{noise, sigma.pred,} \hlkwc{col}\hldef{=}\hlsng{"grey"}\hldef{)}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=0.8\linewidth]{figure/pred-sigma2-1} 

}


\end{knitrout}
\end{frame}






\begin{frame}[fragile]
  \frametitle{Prediction in `unmarked'}
\begin{knitrout}\tiny
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{plot}\hldef{(Predicted} \hlopt{~} \hldef{noise, sigma.pred,} \hlkwc{ylab}\hldef{=}\hlsng{"Scale parameter (sigma)"}\hldef{,}
     \hlkwc{ylim}\hldef{=}\hlkwd{c}\hldef{(}\hlnum{0}\hldef{,}\hlnum{100}\hldef{),} \hlkwc{xlab}\hldef{=}\hlsng{"Noise level"}\hldef{,} \hlkwc{type}\hldef{=}\hlsng{"l"}\hldef{)}
\hlkwd{lines}\hldef{(lower} \hlopt{~} \hldef{noise, sigma.pred,} \hlkwc{col}\hldef{=}\hlsng{"grey"}\hldef{)}
\hlkwd{lines}\hldef{(upper} \hlopt{~} \hldef{noise, sigma.pred,} \hlkwc{col}\hldef{=}\hlsng{"grey"}\hldef{)}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=0.8\linewidth]{figure/pred-sigma2-2-1} 

}


\end{knitrout}
\end{frame}





\subsection{Bayesian inference}




\begin{frame}
  \frametitle{Outline}
  \Large
  \tableofcontents[currentsection,currentsubsection]
\end{frame}



\begin{frame}[fragile]
  \frametitle{\normalsize Conditional-on-$N$ and $n_i=\sum_{j=1}^{J} y_{i,j}$}
\vspace{-3pt}
\begin{knitrout}\tiny
\definecolor{shadecolor}{rgb}{0.961, 0.961, 0.863}\color{fgcolor}\begin{kframe}
\begin{verbatim}
model {

# lambda.intercept ~ dunif(0, 20)
# beta0 <- log(lambda.intercept)
beta0 ~ dnorm(0, 0.1)
beta1 ~ dnorm(0, 0.1)

alpha0 ~ dnorm(0, 0.1)
alpha1 ~ dnorm(0, 0.1)

for(i in 1:nSites) {
  log(lambda[i]) <- beta0 + beta1*elevation[i]
  N[i] ~ dpois(lambda[i]*Area)         # Latent local abundance
  log(sigma[i]) <- alpha0 + alpha1*noise[i]
  for(j in 1:nBins) {
    ## Trick to do integration for *point-transects*
    pbar[i,j] <- (sigma[i]^2 * (1-exp(-b[j+1]^2/(2*sigma[i]^2))) -
                  sigma[i]^2 * (1-exp(-b[j]^2/(2*sigma[i]^2)))) * 
                 2*3.141593/area[j]     
    pi[i,j] <- psi[j]*pbar[i,j]         ## Pr(present and detected in bin j)
  }
  pi[i,nBins+1] <- 1-sum(pi[i,1:nBins]) ## Pr(not detected)
  n[i] ~ dbin(1-pi[i,nBins+1], N[i])
  y[i,] ~ dmulti(pi[i,1:nBins]/(1-pi[i,nBins+1]), n[i])
  ## If N~Pois(lam), then the above is equivalent to:
  # for(j in 1:nBins) { y[i,j] ~ dpois(lambda[i]*pi[i,j])  }
}

totalAbundance <- sum(N[1:nSites])

}
\end{verbatim}
\end{kframe}
\end{knitrout}
\end{frame}





\begin{frame}[fragile]
  \frametitle{Data, inits, and parameters}
  Put data in a named list
  \vspace{-12pt}
\begin{knitrout}\footnotesize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{jags.data.pt} \hlkwb{<-} \hlkwd{list}\hldef{(}\hlkwc{y}\hldef{=y4,} \hlkwc{n}\hldef{=}\hlkwd{rowSums}\hldef{(y4),} \hlkwc{area}\hldef{=}\hlkwd{diff}\hldef{(area),}
                     \hlkwc{b}\hldef{=b,}              \hlcom{# Distance break points}
                     \hlkwc{Area}\hldef{=pi}\hlopt{*}\hldef{B}\hlopt{^}\hlnum{2}\hlopt{/}\hlnum{1e4}\hldef{,}  \hlcom{# Area in ha}
                     \hlkwc{psi}\hldef{=psi,}          \hlcom{# Pr(occuring in bin j)}
                     \hlkwc{elevation}\hldef{=elevation,} \hlkwc{noise}\hldef{=noise,}
                     \hlkwc{nSites}\hldef{=nSites,} \hlkwc{nBins}\hldef{=J)}
\end{alltt}
\end{kframe}
\end{knitrout}
\pause
\vfill
  Initial values
  \vspace{-12pt}
\begin{knitrout}\footnotesize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{jags.inits.pt} \hlkwb{<-} \hlkwa{function}\hldef{() \{}
    \hlkwd{list}\hldef{(}\hlkwc{beta0}\hldef{=}\hlkwd{rnorm}\hldef{(}\hlnum{1}\hldef{),} \hlkwc{alpha0}\hldef{=}\hlkwd{rnorm}\hldef{(}\hlnum{1}\hldef{,} \hlnum{5}\hldef{),}
         \hlkwc{N}\hldef{=}\hlkwd{rowSums}\hldef{(y4)}\hlopt{+}\hlkwd{rpois}\hldef{(}\hlkwd{nrow}\hldef{(y4),} \hlnum{2}\hldef{))}
\hldef{\}}
\end{alltt}
\end{kframe}
\end{knitrout}
\pause
\vfill
  Parameters to monitor
  \vspace{-12pt}
\begin{knitrout}\small
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{jags.pars.pt} \hlkwb{<-} \hlkwd{c}\hldef{(}\hlsng{"beta0"}\hldef{,} \hlsng{"beta1"}\hldef{,}
                  \hlsng{"alpha0"}\hldef{,} \hlsng{"alpha1"}\hldef{,} \hlsng{"totalAbundance"}\hldef{)}
\end{alltt}
\end{kframe}
\end{knitrout}
\end{frame}





\begin{frame}[fragile]
  \frametitle{MCMC}
  \small
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{jags.post.pt} \hlkwb{<-} \hlkwd{jags.basic}\hlstd{(}\hlkwc{data}\hlstd{=jags.data.pt,} \hlkwc{inits}\hlstd{=jags.inits.pt,}
                           \hlkwc{parameters.to.save}\hlstd{=jags.pars.pt,}
                           \hlkwc{model.file}\hlstd{=}\hlstr{"distsamp-point-mod.jag"}\hlstd{,}
                           \hlkwc{n.chains}\hlstd{=}\hlnum{3}\hlstd{,} \hlkwc{n.adapt}\hlstd{=}\hlnum{100}\hlstd{,} \hlkwc{n.burnin}\hlstd{=}\hlnum{0}\hlstd{,}
                           \hlkwc{n.iter}\hlstd{=}\hlnum{2000}\hlstd{,} \hlkwc{parallel}\hlstd{=}\hlnum{TRUE}\hlstd{)}
\end{alltt}
\end{kframe}
\end{knitrout}
\vfill
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{round}\hlstd{(}\hlkwd{summary}\hlstd{(jags.post.pt)}\hlopt{$}\hlstd{quantile,} \hlkwc{digits}\hlstd{=}\hlnum{3}\hlstd{)}
\end{alltt}
\begin{verbatim}
##                    2.5%      25%      50%      75%    97.5%
## alpha0            2.888    2.931    2.956    2.978    3.021
## alpha1           -0.581   -0.543   -0.524   -0.504   -0.470
## beta0             1.879    1.974    2.031    2.088    2.202
## beta1             0.807    0.889    0.932    0.977    1.063
## deviance        646.281  653.905  658.546  663.300  673.042
## totalAbundance 2866.975 3175.000 3347.000 3539.000 3933.000
\end{verbatim}
\end{kframe}
\end{knitrout}
\end{frame}






%\section{Simulation}

\section{Line transects}



\subsection{Simulation}

\begin{frame}
  \frametitle{Outline}
  \Large
%  \tableofcontents[currentsection,currentsubsection]
  \tableofcontents[currentsection]
\end{frame}



\begin{frame}
  \frametitle{Multinomial cell probs for line transects}
  \small
  Definitions needed for computing \alert{bin-specific} $\bar{p}$ and
  multinomial cell probabilities. 
  \begin{itemize}
  \small
    \setlength\itemsep{1pt}
    \item $y_{ij}$ -- number of individuals detected at site $i$ in bin $j$
    \item $\sigma_i$ -- scale parameter of detection function $g(x)$
    \item $b_1, \dots, b_{J+1}$ -- Distance break points defining $J$ distance intervals
    % \item $\bar{p}_j = \int_{b_j}^{b_{j+1}} g(x,\sigma)p(x|b_j\le x<b_{j+1})\, \mathrm{d}x$
    % \item $p(x|b_j\le x<b_{j+1}) = 1/(b_{j+1}-b_j)$
    \item $\bar{p}_j$ -- Average detection probability in distance bin j
    % \item $\psi_j=\Pr(b_j\le x<b_{j+1})=(b_{j+1}-b_j)/B$ % -- Pr(occuring in distance bin $j$)
    \item $\psi_j$ -- Pr(occuring in distance bin $j$)
  \end{itemize}
  \pause \vfill
  \footnotesize
  \begin{columns}
    \column{0.9\paperwidth}
    \begin{tabular}{lc}
      \hline
      \centering
      Description                       & Multinomial cell probability \\
      \hline
      Pr(occurs and detected in first distance bin)  & $\pi_1 = \psi_1\bar{p}_1$   \\
      Pr(occurs and detected in second distance bin)  & $\pi_2 = \psi_2\bar{p}_2$   \\
      {\centering $\cdots$}             & $\cdots$                     \\
      Pr(occurs and detected in last distance bin)  & $\pi_J = \psi_J\bar{p}_J$   \\
      Pr(not detected)                  & $\pi_{K} = 1-\sum_{j=1}^J \pi_j$          \\
      \hline
    \end{tabular}
  \end{columns}
\end{frame}






\begin{frame}[fragile]
  \frametitle{Line transects, no covariates}
  \small
  Abundance
  \vspace{-6pt}
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{B} \hlkwb{<-} \hlnum{100}\hldef{; L} \hlkwb{<-} \hlnum{100}\hldef{; A} \hlkwb{<-} \hlnum{2}\hlopt{*}\hldef{B}\hlopt{*}\hldef{L}\hlopt{/}\hlnum{1e4}  \hlcom{## transect widths, length, and area}
\hldef{nSites} \hlkwb{<-} \hlnum{100}\hldef{; lambda1} \hlkwb{<-} \hlnum{1.3}       \hlcom{## Expected value of density}
\hldef{N1} \hlkwb{<-} \hlkwd{rpois}\hldef{(}\hlkwc{n}\hldef{=nSites,} \hlkwc{lambda}\hldef{=lambda1}\hlopt{*}\hldef{A)}
\end{alltt}
\end{kframe}
\end{knitrout}
  \pause
  \vfill
  Multinomial cell probabilities
  \vspace{-6pt}
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{J} \hlkwb{<-} \hlnum{5}                     \hlcom{# distance bins}
\hldef{sigma} \hlkwb{<-} \hlnum{50}                \hlcom{# scale parameter}
\hldef{b} \hlkwb{<-} \hlkwd{seq}\hldef{(}\hlnum{0}\hldef{, B,} \hlkwc{length}\hldef{=J}\hlopt{+}\hlnum{1}\hldef{)} \hlcom{# distance break points}
\hldef{psi} \hlkwb{<-} \hlkwd{diff}\hldef{(b)}\hlopt{/}\hldef{B}           \hlcom{# Pr(x is in bin j)}
\hldef{pbar1} \hlkwb{<-} \hlkwd{numeric}\hldef{(J)}        \hlcom{# average detection probability}
\hldef{pi1} \hlkwb{<-} \hlkwd{numeric}\hldef{(J}\hlopt{+}\hlnum{1}\hldef{)}        \hlcom{# multinomial cell probs}
\hlkwa{for}\hldef{(j} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{J) \{}
    \hldef{pbar1[j]} \hlkwb{<-} \hlkwd{integrate}\hldef{(}\hlkwa{function}\hldef{(}\hlkwc{x}\hldef{)} \hlkwd{exp}\hldef{(}\hlopt{-}\hldef{x}\hlopt{^}\hlnum{2}\hlopt{/}\hldef{(}\hlnum{2}\hlopt{*}\hldef{sigma}\hlopt{^}\hlnum{2}\hldef{)),}
                          \hlkwc{lower}\hldef{=b[j],} \hlkwc{upper}\hldef{=b[j}\hlopt{+}\hlnum{1}\hldef{])}\hlopt{$}\hldef{value} \hlopt{/} \hlkwd{diff}\hldef{(b)[j]}
    \hldef{pi1[j]} \hlkwb{<-} \hldef{pbar1[j]}\hlopt{*}\hldef{psi[j]}
\hldef{\}}
\hldef{pi1[J}\hlopt{+}\hlnum{1}\hldef{]} \hlkwb{<-} \hlnum{1}\hlopt{-}\hlkwd{sum}\hldef{(pi1[}\hlnum{1}\hlopt{:}\hldef{J])}
\end{alltt}
\end{kframe}
\end{knitrout}
  \pause
  \vfill
  Detections in each distance interval
  \vspace{-6pt}
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{y1.all} \hlkwb{<-} \hlkwd{matrix}\hldef{(}\hlnum{NA}\hldef{,} \hlkwc{nrow}\hldef{=nSites,} \hlkwc{ncol}\hldef{=J}\hlopt{+}\hlnum{1}\hldef{)}
\hlkwa{for}\hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{nSites) \{}
    \hldef{y1.all[i,]} \hlkwb{<-} \hlkwd{rmultinom}\hldef{(}\hlkwc{n}\hldef{=}\hlnum{1}\hldef{,} \hlkwc{size}\hldef{=N1[i],} \hlkwc{prob}\hldef{=pi1)    \}}
\hldef{y1} \hlkwb{<-} \hldef{y1.all[,}\hlnum{1}\hlopt{:}\hldef{J]}  \hlcom{## Drop final cell}
\end{alltt}
\end{kframe}
\end{knitrout}
\end{frame}



\begin{frame}[fragile]
  \frametitle{Observed distances}
  \centering
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{plot}\hldef{(b[}\hlopt{-}\hldef{(J}\hlopt{+}\hlnum{1}\hldef{)]}\hlopt{+}\hlnum{10}\hldef{,} \hlkwd{colSums}\hldef{(y1),} \hlkwc{type}\hldef{=}\hlsng{"h"}\hldef{,} \hlkwc{lwd}\hldef{=}\hlnum{80}\hldef{,} \hlkwc{lend}\hldef{=}\hlnum{2}\hldef{,} \hlkwc{col}\hldef{=}\hlsng{"skyblue4"}\hldef{,}
     \hlkwc{xlim}\hldef{=}\hlkwd{c}\hldef{(}\hlnum{0}\hldef{,}\hlnum{100}\hldef{),} \hlkwc{ylim}\hldef{=}\hlkwd{c}\hldef{(}\hlnum{0}\hldef{,} \hlnum{70}\hldef{),} \hlkwc{xlab}\hldef{=}\hlsng{"Distance"}\hldef{,} \hlkwc{ylab}\hldef{=}\hlsng{"Detections"}\hldef{)}
\end{alltt}
\end{kframe}
\includegraphics[width=0.9\linewidth]{figure/dist-hist2-1} 
\end{knitrout}
\end{frame}




\begin{frame}[fragile]
  \frametitle{Line transects, covariates}
  \small
  Abundance
  \vspace{-6pt}
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{elevation} \hlkwb{<-} \hlkwd{rnorm}\hldef{(nSites)}
\hldef{beta0} \hlkwb{<-} \hlnum{2}\hldef{; beta1} \hlkwb{<-} \hlnum{1}
\hldef{lambda2} \hlkwb{<-} \hlkwd{exp}\hldef{(beta0} \hlopt{+} \hldef{beta1}\hlopt{*}\hldef{elevation)}
\hldef{N2} \hlkwb{<-} \hlkwd{rpois}\hldef{(}\hlkwc{n}\hldef{=nSites,} \hlkwc{lambda}\hldef{=lambda2}\hlopt{*}\hldef{A)}
\end{alltt}
\end{kframe}
\end{knitrout}
  \pause
  \vfill
  Multinomial cell probabilities
  \vspace{-6pt}
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{noise} \hlkwb{<-} \hlkwd{rnorm}\hldef{(nSites)}
\hldef{alpha0} \hlkwb{<-} \hlnum{3}\hldef{; alpha1} \hlkwb{<-} \hlopt{-}\hlnum{0.5}
\hldef{sigma2} \hlkwb{<-} \hlkwd{exp}\hldef{(alpha0} \hlopt{+} \hldef{alpha1}\hlopt{*}\hldef{noise)}
\hldef{pi2} \hlkwb{<-} \hlkwd{matrix}\hldef{(}\hlnum{NA}\hldef{, nSites, J}\hlopt{+}\hlnum{1}\hldef{)} \hlcom{# multinomial cell probs}
\hlkwa{for}\hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{nSites) \{}
  \hlkwa{for}\hldef{(j} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{J) \{}
      \hldef{pi2[i,j]} \hlkwb{<-} \hlkwd{integrate}\hldef{(}\hlkwa{function}\hldef{(}\hlkwc{x}\hldef{)} \hlkwd{exp}\hldef{(}\hlopt{-}\hldef{x}\hlopt{^}\hlnum{2}\hlopt{/}\hldef{(}\hlnum{2}\hlopt{*}\hldef{sigma2[i]}\hlopt{^}\hlnum{2}\hldef{)),}
          \hlkwc{lower}\hldef{=b[j],} \hlkwc{upper}\hldef{=b[j}\hlopt{+}\hlnum{1}\hldef{])}\hlopt{$}\hldef{value} \hlopt{/} \hldef{(b[j}\hlopt{+}\hlnum{1}\hldef{]}\hlopt{-}\hldef{b[j])} \hlopt{*} \hldef{psi[j] \}}
  \hldef{pi2[i,J}\hlopt{+}\hlnum{1}\hldef{]} \hlkwb{<-} \hlnum{1}\hlopt{-}\hlkwd{sum}\hldef{(pi2[i,}\hlnum{1}\hlopt{:}\hldef{J]) \}}
\end{alltt}
\end{kframe}
\end{knitrout}
  \pause
  \vfill
  Detections in each distance interval
  \vspace{-6pt}
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{y2.all} \hlkwb{<-} \hlkwd{matrix}\hldef{(}\hlnum{NA}\hldef{,} \hlkwc{nrow}\hldef{=nSites,} \hlkwc{ncol}\hldef{=J}\hlopt{+}\hlnum{1}\hldef{)}
\hlkwa{for}\hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{nSites) \{}
    \hldef{y2.all[i,]} \hlkwb{<-} \hlkwd{rmultinom}\hldef{(}\hlkwc{n}\hldef{=}\hlnum{1}\hldef{,} \hlkwc{size}\hldef{=N2[i],} \hlkwc{prob}\hldef{=pi2[i,])    \}}
\hldef{y2} \hlkwb{<-} \hldef{y2.all[,}\hlnum{1}\hlopt{:}\hldef{J]}
\end{alltt}
\end{kframe}
\end{knitrout}
\end{frame}






\begin{frame}[fragile]
  \frametitle{Simulated data}
  \begin{columns}
    \begin{column}{0.4\textwidth}
      \small
      Observations
%      \tiny
  \vspace{-6pt}
\begin{knitrout}\tiny
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{y2[}\hlnum{1}\hlopt{:}\hlnum{25}\hldef{,]}
\end{alltt}
\begin{verbatim}
##       [,1] [,2] [,3] [,4] [,5]
##  [1,]    3    2    0    0    0
##  [2,]    4    1    1    0    0
##  [3,]    6    2    3    0    0
##  [4,]    7    4    1    0    0
##  [5,]    2    2    0    0    0
##  [6,]    0    0    0    0    0
##  [7,]    1    0    0    0    0
##  [8,]    5    0    1    0    0
##  [9,]    3    7    2    0    0
## [10,]    5    2    0    0    0
## [11,]    4    2    0    0    0
## [12,]    5    2    0    0    0
## [13,]    2    1    0    0    0
## [14,]   12   10    8    4    1
## [15,]    3    0    0    0    0
## [16,]    3    0    0    0    0
## [17,]    2    0    0    0    0
## [18,]    9    1    0    0    0
## [19,]    7    5    4    0    0
## [20,]    1    1    1    0    0
## [21,]    5    4    2    1    0
## [22,]    1    1    1    3    0
## [23,]    3    2    0    0    0
## [24,]    1    0    1    0    0
## [25,]    7    8    4    1    2
\end{verbatim}
\end{kframe}
\end{knitrout}
  \end{column}
  \begin{column}{0.6\textwidth}
    \pause
%    \scriptsize
    {\centering Summary stats \\}
    \vspace{24pt}
    \small
    Proportion of sites known to be occupied
    \vspace{-6pt}
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{# Max count at each site}
\hldef{maxCounts} \hlkwb{<-} \hlkwd{apply}\hldef{(y2,} \hlnum{1}\hldef{, max)}
\hldef{naiveOccupancy} \hlkwb{<-} \hlkwd{sum}\hldef{(maxCounts}\hlopt{>}\hlnum{0}\hldef{)}\hlopt{/}\hldef{nSites}
\hldef{naiveOccupancy}
\end{alltt}
\begin{verbatim}
## [1] 0.9
\end{verbatim}
\end{kframe}
\end{knitrout}
  \pause
  \vfill
  \small
  Total detections in each distance interval
  \vspace{-6pt}
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{colSums}\hldef{(y2)}
\end{alltt}
\begin{verbatim}
## [1] 360 151  63  32  15
\end{verbatim}
\end{kframe}
\end{knitrout}
  \pause
  \vfill
  Naive abundance
  \vspace{-6pt}
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{sum}\hldef{(y2)}
\end{alltt}
\begin{verbatim}
## [1] 621
\end{verbatim}
\end{kframe}
\end{knitrout}
  \end{column}
  \end{columns}
\end{frame}






%\section{Prediction}
\subsection{Likelihood-based inference}


\begin{frame}
  \frametitle{Outline}
  \Large
  \tableofcontents[currentsection]
\end{frame}






\begin{frame}[fragile]
  \frametitle{Prepare data in `unmarked'}
  \small
  Note the new arguments.
  \vspace{-6pt}
\begin{knitrout}\tiny
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{umf} \hlkwb{<-} \hlkwd{unmarkedFrameDS}\hldef{(}\hlkwc{y}\hldef{=y2,} \hlkwc{siteCovs}\hldef{=}\hlkwd{data.frame}\hldef{(elevation,noise),} \hlkwc{dist.breaks}\hldef{=b,}
                       \hlkwc{tlength}\hldef{=}\hlkwd{rep}\hldef{(L, nSites),} \hlkwc{survey}\hldef{=}\hlsng{"line"}\hldef{,} \hlkwc{unitsIn}\hldef{=}\hlsng{"m"}\hldef{)}
\end{alltt}
\end{kframe}
\end{knitrout}
\pause
\begin{knitrout}\tiny
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{summary}\hldef{(umf)}
\end{alltt}
\begin{verbatim}
## unmarkedFrameDS Object
## 
## line-transect survey design
## Distance class cutpoints (m):  0 20 40 60 80 100 
## 
## 100 sites
## Maximum number of distance classes per site: 5 
## Mean number of distance classes per site: 5 
## Sites with at least one detection: 90 
## 
## Tabulation of y observations:
##   0   1   2   3   4   5   6   7   8   9  10  11  12  15  17  19  28 
## 308  75  39  25  12  10   6   8   6   2   2   1   1   2   1   1   1 
## 
## Site-level covariates:
##    elevation            noise         
##  Min.   :-2.15115   Min.   :-2.80421  
##  1st Qu.:-0.67921   1st Qu.:-0.83893  
##  Median :-0.20250   Median :-0.06717  
##  Mean   :-0.07937   Mean   :-0.18973  
##  3rd Qu.: 0.60327   3rd Qu.: 0.39358  
##  Max.   : 2.03949   Max.   : 1.84018
\end{verbatim}
\end{kframe}
\end{knitrout}
\end{frame}



\begin{frame}[fragile]
  \frametitle{Fit the model}
  \footnotesize
\begin{knitrout}\tiny
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{## fm <- distsamp(~noise ~elevation, umf, keyfun="exp")     # negative exp}
\hlcom{## fm <- distsamp(~noise ~elevation, umf, keyfun="hazard")  # hazard rate}
\hldef{fm} \hlkwb{<-} \hlkwd{distsamp}\hldef{(}\hlopt{~}\hldef{noise} \hlopt{~}\hldef{elevation, umf,} \hlkwc{keyfun}\hldef{=}\hlsng{"halfnorm"}\hldef{)}   \hlcom{# half-normal}
\hldef{fm}
\end{alltt}
\begin{verbatim}
## 
## Call:
## distsamp(formula = ~noise ~ elevation, data = umf, keyfun = "halfnorm")
## 
## Density (log-scale):
##             Estimate     SE    z   P(>|z|)
## (Intercept)     2.05 0.0611 33.5 2.00e-245
## elevation       1.02 0.0489 21.0  1.82e-97
## 
## Detection (log-scale):
##             Estimate     SE     z  P(>|z|)
## (Intercept)    2.929 0.0369  79.4 0.00e+00
## noise         -0.513 0.0312 -16.5 5.68e-61
## 
## AIC: 824.6483 
## Number of sites: 100
## 
## Survey design: line-transect
## Detection function: halfnorm
## UnitsIn: m
## UnitsOut: ha
\end{verbatim}
\end{kframe}
\end{knitrout}
\pause
\vfill
Compare to actual parameter values:
\vspace{-6pt}
\begin{knitrout}\tiny
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{c}\hldef{(}\hlkwc{beta0}\hldef{=beta0,} \hlkwc{beta1}\hldef{=beta1);} \hlkwd{c}\hldef{(}\hlkwc{alpha0}\hldef{=alpha0,} \hlkwc{alpha1}\hldef{=alpha1)}
\end{alltt}
\begin{verbatim}
## beta0 beta1 
##     2     1
## alpha0 alpha1 
##    3.0   -0.5
\end{verbatim}
\end{kframe}
\end{knitrout}
\end{frame}




\subsection{Bayesian inference}


\begin{frame}
  \frametitle{Outline}
  \Large
  \tableofcontents[currentsection,currentsubsection]
\end{frame}





\begin{frame}[fragile]
  \frametitle{\normalsize Conditional-on-$N$ and $n_i=\sum_{j=1}^{J} y_{i,j}$}
\vspace{-3pt}
\begin{knitrout}\tiny
\definecolor{shadecolor}{rgb}{0.961, 0.961, 0.863}\color{fgcolor}\begin{kframe}
\begin{verbatim}
model {

beta0 ~ dnorm(0, 0.1)
beta1 ~ dnorm(0, 0.1)

alpha0 ~ dnorm(0, 0.1)
alpha1 ~ dnorm(0, 0.1)

for(i in 1:nSites) {
  log(lambda[i]) <- beta0 + beta1*elevation[i]
  N[i] ~ dpois(lambda[i]*Area)         # Latent local abundance
  log(sigma[i]) <- alpha0 + alpha1*noise[i]
  tau[i] <- 1/sigma[i]^2
  for(j in 1:nBins) {
    ## Trick to do integration for *line-transects*
    pbar[i,j] <- (pnorm(b[j+1], 0, tau[i]) - pnorm(b[j], 0, tau[i])) /
                  dnorm(0, 0, tau[i]) / (b[j+1]-b[j])
    pi[i,j] <- psi[j]*pbar[i,j]         ## Pr(present and detected in bin j)
  }
  pi[i,nBins+1] <- 1-sum(pi[i,1:nBins]) ## Pr(not detected)
  n[i] ~ dbin(1-pi[i,nBins+1], N[i])
  y[i,] ~ dmulti(pi[i,1:nBins]/(1-pi[i,nBins+1]), n[i])
  ## If N~Pois(lam), then the above is equivalent to:
  # for(j in 1:nBins) { y[i,j] ~ dpois(lambda[i]*pi[i,j])  }
}

totalAbundance <- sum(N[1:nSites])

}
\end{verbatim}
\end{kframe}
\end{knitrout}
\end{frame}





\begin{frame}[fragile]
  \frametitle{Data, inits, and parameters}
  Put data in a named list
  \vspace{-12pt}
\begin{knitrout}\footnotesize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{jags.data.line} \hlkwb{<-} \hlkwd{list}\hldef{(}\hlkwc{y}\hldef{=y2,} \hlkwc{n}\hldef{=}\hlkwd{rowSums}\hldef{(y2),}
                       \hlkwc{b}\hldef{=b,}           \hlcom{# Distance break points}
                       \hlkwc{psi}\hldef{=}\hlkwd{diff}\hldef{(b)}\hlopt{/}\hldef{B,} \hlcom{# Pr(occuring in bin j)}
                       \hlkwc{Area}\hldef{=A,}        \hlcom{# Area in ha}
                       \hlkwc{elevation}\hldef{=elevation,} \hlkwc{noise}\hldef{=noise,}
                       \hlkwc{nSites}\hldef{=nSites,} \hlkwc{nBins}\hldef{=J)}
\end{alltt}
\end{kframe}
\end{knitrout}
\pause
\vfill
  Initial values
  \vspace{-12pt}
\begin{knitrout}\footnotesize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{jags.inits.line} \hlkwb{<-} \hlkwa{function}\hldef{() \{}
    \hlkwd{list}\hldef{(}\hlkwc{beta0}\hldef{=}\hlkwd{rnorm}\hldef{(}\hlnum{1}\hldef{),} \hlkwc{alpha0}\hldef{=}\hlkwd{rnorm}\hldef{(}\hlnum{1}\hldef{,} \hlnum{5}\hldef{),}
         \hlkwc{N}\hldef{=}\hlkwd{rowSums}\hldef{(y2)}\hlopt{+}\hlkwd{rpois}\hldef{(}\hlkwd{nrow}\hldef{(y2),} \hlnum{2}\hldef{))}
\hldef{\}}
\end{alltt}
\end{kframe}
\end{knitrout}
\pause
\vfill
  Parameters to monitor
  \vspace{-12pt}
\begin{knitrout}\small
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{jags.pars.line} \hlkwb{<-} \hlkwd{c}\hldef{(}\hlsng{"beta0"}\hldef{,} \hlsng{"beta1"}\hldef{,}
                    \hlsng{"alpha0"}\hldef{,} \hlsng{"alpha1"}\hldef{,} \hlsng{"totalAbundance"}\hldef{)}
\end{alltt}
\end{kframe}
\end{knitrout}
\end{frame}





\begin{frame}[fragile]
  \frametitle{MCMC}
  \small
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{library}\hlstd{(jagsUI)}
\hlstd{jags.post.line} \hlkwb{<-} \hlkwd{jags.basic}\hlstd{(}\hlkwc{data}\hlstd{=jags.data.line,} \hlkwc{inits}\hlstd{=jags.inits.line,}
                             \hlkwc{parameters.to.save}\hlstd{=jags.pars.line,}
                             \hlkwc{model.file}\hlstd{=}\hlstr{"distsamp-line-mod.jag"}\hlstd{,}
                             \hlkwc{n.chains}\hlstd{=}\hlnum{3}\hlstd{,} \hlkwc{n.adapt}\hlstd{=}\hlnum{100}\hlstd{,} \hlkwc{n.burnin}\hlstd{=}\hlnum{0}\hlstd{,}
                             \hlkwc{n.iter}\hlstd{=}\hlnum{2000}\hlstd{,} \hlkwc{parallel}\hlstd{=}\hlnum{TRUE}\hlstd{)}
\end{alltt}
\end{kframe}
\end{knitrout}
\vfill
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{round}\hlstd{(}\hlkwd{summary}\hlstd{(jags.post.line)}\hlopt{$}\hlstd{quantile,} \hlkwc{digits}\hlstd{=}\hlnum{3}\hlstd{)}
\end{alltt}
\begin{verbatim}
##                    2.5%      25%      50%      75%    97.5%
## alpha0            2.854    2.903    2.927    2.951    2.999
## alpha1           -0.579   -0.536   -0.514   -0.493   -0.457
## beta0             1.928    2.010    2.055    2.097    2.175
## beta1             0.921    0.981    1.014    1.049    1.116
## deviance        768.043  779.454  785.847  792.469  805.876
## totalAbundance 1938.000 2052.000 2122.000 2190.000 2323.000
\end{verbatim}
\end{kframe}
\end{knitrout}
\end{frame}


\begin{frame}[fragile]
  \frametitle{Traceplots and density plots}
\begin{knitrout}\footnotesize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{plot}\hlstd{(jags.post.line[,jags.pars.line[}\hlnum{1}\hlopt{:}\hlnum{3}\hlstd{]])}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=0.7\textwidth]{figure/bugs-plot1-rem2-1} 

}


\end{knitrout}
\end{frame}



\begin{frame}[fragile]
  \frametitle{Traceplots and density plots}
\begin{knitrout}\footnotesize
\definecolor{shadecolor}{rgb}{0.878, 0.918, 0.933}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{plot}\hlstd{(jags.post.line[,jags.pars.line[}\hlnum{4}\hlopt{:}\hlnum{5}\hlstd{]])}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=0.7\textwidth]{figure/bugs-plot2-rem2-1} 

}


\end{knitrout}
\end{frame}





\section{Summary}


\begin{frame}
  \frametitle{Distance sampling summary}
  Assumptions
  \begin{itemize}
    \small
    \item Animals don't move during the survey
    \item Animals are uniformly distributed with respect to the
      transects
    \item Detection is certain on the transect, i.e. $p=1$ when $x=0$. 
    \item Detections are independent
  \end{itemize}
  \pause
  \vfill
  \small
  If these assumptions can be met, distance sampling is a powerful
  method allowing for inference about abundance and density using data
  from a single visit. \\
\end{frame}



\section{Assignment}




\begin{frame}[fragile]
  \frametitle{Assignment}
  % \small
  \footnotesize
  Create a self-contained R script or Rmarkdown file to do the following:
  \vfill
  \begin{enumerate}
%    \small
    \footnotesize
    \item Fit a distance sampling model with a half-normal detection
      function and the following covariates to the black-throated blue
      warbler data ({\tt btbw\_data\_distsamp.csv}) in `unmarked' and
      `JAGS':   
      \begin{itemize}
        \footnotesize
        \item Density covariates: {\tt Elevation, UTM.N, UTM.W}
        \item Detection covariates: {\tt Wind, Noise}
        \item Response: {\scriptsize \tt btbw0\_20, btbw20\_40, btbw40\_60, btbw60\_80, btbw80\_100}
      \end{itemize}
    \item Using the model fitted in `unmarked', create two graphs of
      the predictions: one for density and the other for the scale
      parameter ($\sigma$).
    %% \item Compare the half-normal model to two other models with the
    %%   same covariates, but with negative exponential and hazard
    %%   rate detection functions. Which has the lowest AIC? Do this with
    %%   `unmarked', not JAGS.  
  \end{enumerate}
%  \pause
  \vfill
  Suggestions:
  \begin{itemize}
    \item Convert response variables to matrix with \inr{as.matrix}
    \item Standardize covariates
  \end{itemize}
%  \pause
  \vfill
  Upload your {\tt .R} or {\tt .Rmd} file to ELC by 5:00pm on Tuesday. 
\end{frame}





\end{document}

