project:
  type: website
  output-dir: docs/

website:
  title: "Inference for Models of Fish and Wildlife Population Dynamics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: IPD-syllabus.qmd
        text: Syllabus

format:
  html:
    theme: cosmo
    toc: true
  revealjs:
    theme: simple
    slide-number: true
    chalkboard: true

execute:
  freeze: auto
