---
title: Inference for models of Fish and Wildlife Population Dynamics
subtitle: WILD/FISH 8390
author:
  name: Richard Chandler
  affiliation:
    name: Warnell School of Forestry and Natural Resources, University of Georgia
format: html
---

## Course Description

Recently developed statistical tools make it possible to fit models of population dynamics to field data while accounting for observation error. This course will explain how to use these tools for statistical inference and prediction about animal population parameters including abundance, occupancy, survival, recruitment, and dispersal.

## Course Objectives and Learning Outcomes

By the end of the course, students will know how to (1) design studies of wildlife population dynamics, (2) fit statistical models to data collected in the field, (3) interpret results, and (4) make predictions useful for informing conservation decisions.




## Lectures




### Background

#### Week 1 - Classical statistical  models

- [Lecture 1 - Introduction](lectures/intro/lecture-intro.qmd)

- [Lecture 2 - Linear and generalized linear models](lectures/stats-basics/lecture-stats-basics.qmd)

#### Week 2 - Occupancy models

- Lecture 3


### Static models


### Dynamic models
