---
format: html
---

Inference for Models of Fish and Wildlife\
Population Dynamics

WILD(FISH) 8390\
Lecture: Tues, Thurs 1:15--2:35 PM\
Room 4-516, Warnell\

  --------------- --------------------------- -- -------------------------
                        **Instructor**            **Teaching Assistant**
                     Dr. Richard Chandler                Jen Brown
  Office room:               3-407                         4-219
  Email:           rchandler@warnell.uga.edu      jennifer.brown1@uga.edu
  Office hours:         Thur 2:45--3:45               Fri 11:30--1:30
  --------------- --------------------------- -- -------------------------

# Course Description {#course-description .unnumbered}

Recently developed statistical tools make it possible to fit models of
population dynamics to field data while accounting for observation
error. This course will explain how to use these tools for statistical
inference and prediction about animal population parameters including
abundance, occupancy, survival, recruitment, and dispersal.

# Course Objectives and Learning Outcomes {#course-objectives-and-learning-outcomes .unnumbered}

By the end of the course, students will know how to (1) design studies
of wildlife population dynamics, (2) fit statistical models to data
collected in the field, (3) interpret results, and (4) make predictions
useful for informing conservation decisions.

# Textbooks {#textbooks .unnumbered}

- (AHM1) Kéry, M. and J.A. Royle. 2016. Applied Hierarchical Modeling in
  Ecology: Analysis of Distribution, Abundance and Species Richness in R
  and BUGS : Volume 1: Prelude and Static Models. Academic Press.
  [[eBook]{style="color: blue"}](https://www.sciencedirect.com/book/9780128013786/applied-hierarchical-modeling-in-ecology).

- (AHM2) Kéry, M. and J.A. Royle. 2020. Applied Hierarchical Modeling in
  Ecology: Analysis of Distribution, Abundance and Species Richness in R
  and BUGS : Volume 2: Dynamic and Advanced Models. Academic Press.
  [[eBook]{style="color: blue"}](https://www.sciencedirect.com/book/9780128237687/applied-hierarchical-modeling-in-ecology-analysis-of-distribution-abundance-and-species-richness-in-r-and-bugs).

- (SCR) Royle, J.A., R.B. Chandler, R. Sollmann, and B. Gardner. 2013.
  Spatial Capture-Recapture. Academic Press. Download chapters of the
  eBook from the UGA library
  [[eBook]{style="color: blue"}](https://www-sciencedirect-com.proxy-remote.galib.uga.edu/book/9780124059399/spatial-capture-recapture).

# Grading {#grading .unnumbered}

::: center
                             Quantity   Grade percentage
  ------------------------ ---------- ------------------
  Weekly assignments$^*$           15                45%
  Final presentation                1                20%
  Final paper$^{*}$                 1                30%
  Class participation                                 5%

\
$^*$Late assignments will be penalized 3 points/day, up to a maximum of
50 points off.\
:::

The plus/minus grading system will be used, according to UGA policy, and
assigned following this plus/minus grading scale: A =
$>$`<!-- -->`{=html}93-100, A- = $>$`<!-- -->`{=html}90-93, B+ =
$>$`<!-- -->`{=html}87-90, B = $>$`<!-- -->`{=html}83-87, B- =
$>$`<!-- -->`{=html}80-83, C+ = $>$`<!-- -->`{=html}77-80, C =
$>$`<!-- -->`{=html}73-77, C-= $>$`<!-- -->`{=html}70-73, D = 60-70, F =
$<$`<!-- -->`{=html}60.

# Attendance {#attendance .unnumbered}

Attendance is optional, but it will be difficult to succeed if you don't
participate in lectures.

# Academic Honesty {#academic-honesty .unnumbered}

As a University of Georgia student, you have agreed to abide by the UGA
academic honesty policy. UGA Student Honor code: "I will be academically
honest in all of my academic work and will not tolerate academic
dishonesty of others". A Culture of Honesty, the University's policy and
procedures for handling cases of suspected dishonesty, can be found at
[here](https://honesty.uga.edu/). You are responsible for informing
yourself about the university's standards before performing any academic
work. Lack of knowledge of the academic honesty policy is not a
reasonable explanation for a violation. Please ask if you have questions
related to course assignments and the academic honesty policy. Any form
of possible academic dishonesty will be reported to the UGA Office of
the Vice President for Instruction.

# Generative AI {#generative-ai .unnumbered}

Artificial intelligence (AI) tools, like chatGPT and other generative AI
chatbots, can be useful for improving text and computer code. However,
they can also hinder learning if used to generate answers and bypass
critical thinking. Students must disclose the use of generative AI for
completing assignments, including the final paper. If a student decides
to use generative AI, it can only be used to improve text and code
written by the student. AI tools cannot be used to create answers by
inputting assignment questions into prompts. Students must report the
prompts provided to AI tools, along with the original text (or code) and
the final text. Prompts and output can be disclosed by providing a link
to the AI chat.

# Academic Coaching {#academic-coaching .unnumbered}

Assistance with time management, test and performance anxiety,
notetaking, motivation, text comprehension, test preparation, and other
barriers to success at UGA. [
Link](https://dae.uga.edu/services/academic-coaching/) for the Office of
Academic Enhancement.

# Accommodations for Disabilities {#accommodations-for-disabilities .unnumbered}

If you require a disability-required accommodation, it is essential that
you register with the [Disability Resource Center](https://drc.uga.edu)
(Clark Howell Hall; 706-542-8719) and notify me of your eligibility for
reasonable accommodations. We can then plan how best to coordinate your
accommodations. Please note that accommodations cannot be provided
retroactively.

# UGA Well-Being Resources {#uga-well-being-resources .unnumbered}

UGA Well-being Resources promote student success by cultivating a
culture that supports a more active, healthy, and engaged student
community. Anyone needing assistance is encouraged to contact Student
Care & Outreach (SCO) in the Division of Student Affairs at 706-542-8479
or visit [sco.uga.edu](sco.uga.edu){.uri}. Student Care & Outreach helps
students navigate difficult circumstances by connecting them with the
most appropriate resources or services. They also administer the
Embark@UGA program which supports students experiencing, or who have
experienced, homelessness, foster care, or housing insecurity.

UGA provides both clinical and non-clinical options to support student
well-being and mental health, any time, any place. Whether on campus, or
studying from home or abroad, UGA Well-being Resources are here to help.

Student Care and Outreach: [sco.uga.edu](sco.uga.edu){.uri}

University Health Center:
[healthcenter.uga.edu](healthcenter.uga.edu){.uri}

Counseling & Psychiatric Services: [caps.uga.edu](caps.uga.edu){.uri} or
CAPS 24/7 crisis support 706-542-2273

Health Promotion/ Fontaine Center:
[healthpromotion.uga.edu](healthpromotion.uga.edu){.uri}

Accessibility and Testing:
[accessibility.uga.edu](accessibility.uga.edu){.uri}

Additional information, including free digital well-being resources, can
be accessed through the UGA app or by visiting
<https://well-being.uga.edu>.

# Tentative Course Outline {#tentative-course-outline .unnumbered}

::: center
+-----------+----------------------------+----------------------------+
| **Date**  | **Lecture**                | **Reading**                |
+:==========+:===========================+:===========================+
| PART 1 -- BACKGROUND                                                |
+-----------+----------------------------+----------------------------+
| Aug 18    | Introduction and linear    | AHM1 Foreword, Preface,    |
|           | models                     | Chapter 1                  |
+-----------+----------------------------+----------------------------+
| Aug 20    | Generalized linear models  | AHM1 Chapter 3             |
+-----------+----------------------------+----------------------------+
| PART 2 -- STATIC MODELS                                             |
+-----------+----------------------------+----------------------------+
| Aug 25    | Occupancy models           | AHM1 Ch 4 and Ch 10 (pp    |
|           |                            | 551--564)                  |
+-----------+----------------------------+----------------------------+
| Aug 27    | Occupancy models           |                            |
+-----------+----------------------------+----------------------------+
| Sept 1    | Occupancy models           | AHM1 Chapter 10 (pp        |
|           |                            | 564--600)                  |
+-----------+----------------------------+----------------------------+
| Sept 3    | Occupancy models           | AHM1 Chapter 10 (pp        |
|           |                            | 591--600)                  |
+-----------+----------------------------+----------------------------+
| Sept 8    | Binomial $N$-mixture       | AHM1 Chapter 6 (pp         |
|           | models                     | 219--228)                  |
+-----------+----------------------------+----------------------------+
| Sept 10   | Prior predictive checks    | AHM1 Chapter 6 (pp         |
|           |                            | 229--245)                  |
+-----------+----------------------------+----------------------------+
| Sept 15   | Model selection and fit    | AHM1 Chapter 6 (pp         |
|           | assessment                 | 245--254)                  |
+-----------+----------------------------+----------------------------+
| Sept 17   | Causal inference           | AHM1 Chapter 6 (pp         |
|           |                            | 254--312)                  |
+-----------+----------------------------+----------------------------+
| Sept 22   | Multinomial $N$-mixture    | AHM1 Chapter 7 (pp         |
|           | models                     | 313--334)                  |
+-----------+----------------------------+----------------------------+
| Sept 24   | Multinomial $N$-mixture    | AHM1 Chapter 7 (pp         |
|           | models                     | 334--391)                  |
+-----------+----------------------------+----------------------------+
| Sept 29   | Hierarchical distance      | AHM1 Chapter 8 (pp         |
|           | sampling                   | 426--460)                  |
+-----------+----------------------------+----------------------------+
| Oct 1     | Conventional distance      | AHM1 Chapter 8 (pp         |
|           | sampling                   | 393--426)                  |
+-----------+----------------------------+----------------------------+
| Oct 6     | Non-spatial                | SCR Chapters 1--4          |
|           | capture-recapture          |                            |
+-----------+----------------------------+----------------------------+
| Oct 8     | Spatial capture-recapture  | SCR Chapter 5              |
+-----------+----------------------------+----------------------------+
| Oct 13    | Spatial capture-recapture  | SCR Chapter 7              |
+-----------+----------------------------+----------------------------+
| Oct 15    | Spatial capture-recapture  | SCR Chapters 9             |
+-----------+----------------------------+----------------------------+
| PART 3 -- DYNAMIC MODELS                                            |
+-----------+----------------------------+----------------------------+
| Oct 20    | Dynamic occupancy models   | AHM2 Ch4 (Due: first       |
|           |                            | draft)                     |
+-----------+----------------------------+----------------------------+
| Oct 22    | Dynamic $N$-mixture models | AHM2 Chapter 2             |
+-----------+----------------------------+----------------------------+
| Oct 27    | Survival models            | AHM2 Chapter 3             |
+-----------+----------------------------+----------------------------+
| Oct 29    | Cormack-Jolly-Seber models | SCR Chapter 16             |
+-----------+----------------------------+----------------------------+
| Nov 3     | Jolly-Seber models         | SCR Chapter 16 (Due: peer  |
|           |                            | review)                    |
+-----------+----------------------------+----------------------------+
| Nov 5     | Jolly-Seber models         | SCR Chapter 16             |
+-----------+----------------------------+----------------------------+
| Nov 10    | Dynamic spatial            | SCR Chapter 16             |
|           | capture-recapture models   |                            |
+-----------+----------------------------+----------------------------+
| Nov 12    | Dynamic spatial            | SCR Chapter 16             |
|           | capture-recapture models   |                            |
+-----------+----------------------------+----------------------------+
| Nov 17    | Student presentations      |                            |
+-----------+----------------------------+----------------------------+
| Nov 19    | Student presentations      |                            |
+-----------+----------------------------+----------------------------+
| Nov 24    | Thanksgiving Break         |                            |
+-----------+----------------------------+----------------------------+
| Nov 26    | Thanksgiving Break         |                            |
+-----------+----------------------------+----------------------------+
| Dec 1     | No class (Friday schedule) | Due: Final paper           |
+-----------+----------------------------+----------------------------+
:::

The course syllabus is a general plan for the course; deviations
announced to the class by the instructor may be necessary.
