---
format: html
lang: en
---

# Final Project Guidelines <br> Inference for Models of Fish and Wildlife <br> Population Dynamics <br> WILD 8390

## Overview {#overview .unnumbered}

Each student will write a short (3--5 page) scientific paper supported
by an analysis of either real or simulated data using one of the models
covered during this semester. The paper will be submitted along with a
self-contained R script (or .qmd or .Rmd file), and data.

## Paper structure {#paper-structure .unnumbered}

Abstract (1 paragraph, $<$500 words)<br>
Briefly describe the motivation, methods, results, and implications.

Introduction ($>$`<!-- -->`{=html}2 paragraphs)<br>
Describe motivation for the study and background information. Cite prior
research.

Methods ($>$`<!-- -->`{=html}2 paragraphs)<br>
Describe study area, study species, study design, data collection, and
data analysis. Emphasize the model description and include equations.

Results ($>$`<!-- -->`{=html}1 paragraph)<br>
Describe key findings, and support them with references to figures and
tables.

Discussion ($>$`<!-- -->`{=html}1 paragraph)<br>
Explain how your results advance knowledge and inform conservation
efforts. Connect your results to previously published work.

Literature Cited ($>$`<!-- -->`{=html}3 citations)<br>
Use any peer-reviewed journal format you like, and be consistent.

Tables and Figures<br>
Include at least 1 table and 2 figures, along with clear, informative
captions.

## Timeline {#timeline .unnumbered}

- Sept 25: Email instructors with brief (1 paragraph) description of
  project idea

- Oct 28: Submit first draft (later than the syllabus says)

- Oct 28--Nov 21: Meet with Dr. Chandler to discuss first draft

- Nov 11: Submit peer review

- Nov 20 & Nov 25: Presentations

- Dec 2: Submit final paper, code, and data

## Grading {#grading .unnumbered}

The project comprises 30% of your overall grade, and will be graded as
follows:

- First draft: 10%

  - No Results or Discussion required, but you must submit an R script.

  - The analysis does not need to be complete, but you should make
    substantial progress.

- Meeting with Dr. Chandler: 10%

- Peer review: 10%

  - Write your review as you would for a peer-reviewed journal. Good
    advice can be found
    [[here](https://www.britishecologicalsociety.org/wp-content/uploads/2017/06/BES-Peer-Review-Guide-2017_web.pdf)]{style="color: blue"}
    and
    [[here](https://www.nature.com/articles/d41586-018-06991-0)]{style="color: blue"}.

  - Each of your two reviews should be 1-2 pages, including sections for
    "general comments" and "specific comments."

- Final paper: 60%

  - Will be graded based on criteria listed above under "Paper
    structure". It should also incorporate suggestions from peer-review
    and from the presentations.

- Analysis: 10%

  - R code should be easy to follow and annotated

  - We should be able to reproduce results reported in the paper

  - Script should not throw errors

  - Script should not include lengthy data formatting code. Format the
    data elsewhere, and then import it ready for analysis.

The 10-min presentation counts towards an additional 20% of your overall
grade. The presentation should include background information, methods,
results, and conclusions.
