{
  "hash": "7181df3b8b95d791617b0250e9bab649",
  "result": {
    "engine": "knitr",
    "markdown": "---\n## title: \"Converted Presentation\"\nformat:\n  revealjs:\n    theme: default\n    pagetitle: 'Distance sampling'\n    slide-number: true\n    echo: true\nlang: en\n---\n\n\n## {content-align=\"center\" style=\"font-size: 140%;\"}\n\n<br>\n\n<center>\n  \nLecture 8 -- Hierarchical distance sampling: <br>\nsimulation, fitting, and prediction\n\n<br>\n  \n::: {style='font-size: 80%;'}\nWILD(FISH) 8390 <br>\nInference for Models of Fish and Wildlife Population Dynamics <br>\n:::\n  \n</center>\n\n\n\n\n# Overview\n\n## Distance sampling overview\n\nDistance sampling is one of the oldest wildlife sampling methods.\n\n<br>\n\nIt's based on the simple idea that detection probability should decline with distance between an animal and a transect.\n  \n<br>\n\nIf we can estimate the function describing how $p$ declines with distance $x$, we can estimate abundance... if certain assumptions hold, as always.\n\n\n## Distance sampling overview\n\n::: {style='font-size: 80%;'}\nThe simplest estimator of abundance is \n$$\n  \\hat{N} = \\frac{n}{\\hat{p}}\n$$\nwhere $n$ is the number of individuals detected, $p$ is detection probability, and $E(n)=Np$.\n  \n  \n::: {.fragment}\nIn distance sampling, detection probability is a *function* of distance, rather than a constant, such that all individuals have unique detection probabilities.\n:::\n  \n  \n::: {.fragment}\nAs a result, we have to replace $p$ with *average* detection probability:\n$$\n  \\hat{N} = \\frac{n}{\\hat{\\bar{p}}}\n$$\n:::\n  \n  \n::: {.fragment}\nHow do we compute average detection probability ($\\bar{p}$)?\n:::\n:::\n\n\n\n## Detection functions\n\n::: {style='font-size: 80%;'}\nTo estimate average detection probability ($\\bar{p}$), we need:\n  \n- A detection function $g(x)$ describing how $p$ declines with distance.\n- A probability distribution $p(x)$ describing the distances of all animals (detected and not detected).\n  \n  \nThe most common detection functions are:\n  \nDetection function   | $g(x)$\n------------------   | -------\nHalf normal          | $\\exp(-x^2 / (2\\sigma^2))$\nNegative exponential | $\\exp(-x/\\sigma)$\nHazard rate          | $1-\\exp(-(x/a)^{-b})$\n:::\n\n\n## Half-normal\n\n::: {style='font-size: 80%;'}\n$$\n    g(x,\\sigma) = \\exp(-x^2/(2\\sigma^2))\n$$\n  \n  \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsigma1 <- 25; sigma2 <- 50\nplot(function(x) exp(-x^2/(2*sigma1^2)), from=0, to=100, \n     xlab=\"Distance (x)\", ylab=\"Detection probability (p)\")\nplot(function(x) exp(-x^2/(2*sigma2^2)), from=0, to=100, add=TRUE, col=4)\nlegend(70, 1, c(\"sigma=25\", \"sigma=50\"), lty=1, col=c(\"black\",\"blue\"))\n```\n\n::: {.cell-output-display}\n![](lecture-distsamp-HDS_files/figure-revealjs/hn-1.png){fig-align='center' width=70%}\n:::\n:::\n\n:::\n\n\n## Negative exponential\n\n::: {style='font-size: 80%;'}\n$$\n    g(x,\\sigma) = \\exp(-x/\\sigma)\n$$\n  \n  \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsigma1 <- 25; sigma2 <- 50\nplot(function(x) exp(-x/sigma1), from=0, to=100, \n     xlab=\"Distance (x)\", ylab=\"Detection probability (p)\")\nplot(function(x) exp(-x/sigma2), from=0, to=100, add=TRUE, col=4)\nlegend(70, 1, c(\"sigma=25\", \"sigma=50\"), lty=1, col=c(\"black\",\"blue\"))\n```\n\n::: {.cell-output-display}\n![](lecture-distsamp-HDS_files/figure-revealjs/nexp-1.png){fig-align='center' width=70%}\n:::\n:::\n\n:::\n\n\n\n\n## Hazard rate\n\n::: {style='font-size: 80%;'}\n$$\n    g(x,a,b) = 1-\\exp(-(x/a)^{-b})\n$$\n  \n  \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\na1 <- 25; a2 <- 50; b1 <- 2; b2 <- 10\nplot(function(x) 1-exp(-(x/a1)^(-b1)), from=0, to=100, \n     xlab=\"Distance (x)\", ylab=\"Detection probability (p)\", ylim=0:1)\nplot(function(x) 1-exp(-(x/a2)^(-b2)), from=0, to=100, add=TRUE, col=4)\nlegend(70, 1, c(\"a=25, b=2\", \"a=50, b=10\"), lty=1, col=c(\"black\",\"blue\"))\n```\n\n::: {.cell-output-display}\n![](lecture-distsamp-HDS_files/figure-revealjs/haz-1.png){fig-align='center' width=70%}\n:::\n:::\n\n:::\n\n\n## Average detection probability\n\n::: {style='font-size: 80%;'}\nRegardless of the chosen detection function, average detection probability is defined as: \n$$\n     \\bar{p} = \\int_{0}^{B} g(x)p(x) \\; \\mathrm{d}x\n$$\nwhere $B$ is the width of the transect.\n  \n::: {style='font-size: 80%;'}\nAll that remains is the specification of $p(x)$, the distribution of distances (between animals and the transect). \n:::\n  \n::: {style='font-size: 80%;'}\nTo understand why $p(x)$ is needed, think about it this way:\n  \n- If most animals are close to the transect, $\\bar{p}$ would be high\n- If most animals are far from the transect, $\\bar{p}$ would be low\n:::\n:::\n\n\n\n## What should we use for *p(x)*?\n\n::: {style='font-size: 80%;'}\nWhat distribution should we use for the distances between animals and transects?\n\n::: {.fragment}\nIn *line-transect sampling*, it is often assumed that animals are uniformly distributed with respect to the transect.\n  \n- Consequently, $p(x) = 1/B$, where $x$ is the *perpendicular* distance between animal and transect\n- This is guaranteed by random transect placement\n- Can also be justified if animals are neither attracted to the transects or avoid them. \n:::\n  \n::: {.fragment}\nIn *point-transect sampling*, we make the same assumptions, but we recognize that area increases with distance from a point.\n  \n- Consequently, $p(x) = 2x/B^2$ (see pg. 408 in AHM)\n- Here, $x$ is the *radial* distance to an animal\n:::\n:::\n  \n\n## [Computing average *p* for line transects]{style=\"font-size: 90%;\"}\n\nHalf-normal detection function and line-transect sampling.\n  \n\n::: {.cell}\n\n```{.r .cell-code}\nB <- 100                                         # Transect width\ng <- function(x, sigma=25) exp(-x^2/(2*sigma^2)) # g(x)\npdf <- function(x) 1/B                           # p(x), constant\n```\n:::\n\n\nDo the integration\n  \n\n::: {.cell}\n\n```{.r .cell-code}\ngp <- function(x) g(x)*pdf(x)\n(pbar <- integrate(gp, lower=0, upper=B)$value)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3133087\n```\n\n\n:::\n:::\n\n\n31.3\\% chance of detecting an individual within 100 m.\n\n\n## [Computing average *p* for point transects]{style=\"font-size: 90%;\"}\n\nHalf-normal detection function and point-transect sampling.\n  \n\n::: {.cell}\n\n```{.r .cell-code}\nB <- 100                                         # Transect width\ng <- function(x, sigma=25) exp(-x^2/(2*sigma^2)) # g(x)\npdf <- function(x) 2*x/B^2                       # p(x)\n```\n:::\n\n\n\nDo the integration\n  \n\n::: {.cell}\n\n```{.r .cell-code}\ngp <- function(x) g(x)*pdf(x)\n(pbar <- integrate(gp, lower=0, upper=B)$value)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1249581\n```\n\n\n:::\n:::\n\n\n12.5\\% chance of detecting an individual within 100 m. <br>\n\n\n## Shiny App\n\n[Distance Sampling Shiny App](https://richard-chandler.shinyapps.io/distance-sampling/)\n      \n\n## [Conventional vs hierarchical distance sampling]{style=\"font-size: 90%;\"}\n\n::: {style='font-size: 80%;'}\n*Conventional* distance sampling\n  \n* Focus is on estimation of detection function parameters and density\n* No model for spatial variation in density\n* Data are individual-level distances\n* We'll deal with CDS in more depth as a prelude to spatial-capture recapture\n  \n*Hierarchical* distance sampling\n  \n* Focus is on estimation of detection function parameters and spatial variation in abundance/density\n* Data are counts of individuals in each distance bin\n* Multinomial $N$-mixture model with a unique function for computing the multinomial cell probabilities \n \n:::\n \n\n\n\n\n\n\n## Hierarchical distance sampling\n  \n::: {style='font-size: 80%;'}\nState model (with Poisson assumption)\n$$\n    \\mathrm{log}(\\lambda_i) = \\beta_0 + \\beta_1 {w_{i1}} +\n    \\beta_2 {w_{i2}} + \\cdots \\\\\n    N_i \\sim \\mathrm{Poisson}(\\lambda_i)\n$$\n  \nObservation model\n$$\n    \\mathrm{log}(\\sigma_{i}) = \\alpha_0 + \\alpha_1 {w_{i1}}\n    + \\alpha_2 {w_{i3}} + \\cdots //\n    \\{y_{i1}, \\dots, y_{iK}\\}  \\sim \\mathrm{Multinomial}(N_i,\n    \\pi(x, \\sigma_i))\n$$\n:::\n  \n  \nDefinitions <br>\n::: {style='font-size: 60%;'}\n  $\\lambda_i$ -- Expected value of abundance at site $i$ <br>\n  $N_i$ -- Realized value of abundance at site $i$ <br>\n  $\\sigma_{i}$ -- Scale parameter of detection function $g(x)$ at site $i$ <br>\n  $\\pi(x,\\sigma_i)$ -- Function computing multinomial cell probs <br>\n  $y_{ij}$ -- count for distance bin $j$ (final count is unobserved) <br>\n  $w_1$, $w_2$, $w_3$ -- site covariates % %<br>\n:::\n\n\n\n\n\n\n\n# Point transects\n\n## Multinomial cell probs for point transects\n  \n  Definitions needed for computing \\alert{bin-specific} $\\bar{p}$ and\n  multinomial cell probabilities. \n    \n* $y_{ij}$ -- number of individuals detected at site $i$ in bin $j$\n* $\\sigma_i$ -- scale parameter of detection function $g(x)$\n* $b_1, \\dots, b_J$ -- Distance break points defining $J$\n      distance intervals\n* $\\bar{p}_j$ -- Average detection probability in distance interval $j$.\n* $\\psi_j$ -- Probability of occuring in distance band $j$\n  \n   \n::: columns\n    \\begin{tabular}{lc}\n      \\hline\n      \n      Description                       & Multinomial cell probability <br>\n      \\hline\n      Pr(occurs and detected in first distance bin)  & $\\pi_1 = \\psi_1\\bar{p}_1$   <br>\n      Pr(occurs and detected in second distance bin)  & $\\pi_2 = \\psi_2\\bar{p}_2$   <br>\n      { $\\cdots$}             & $\\cdots$                     <br>\n      Pr(occurs and detected in last distance bin)  & $\\pi_J = \\psi_J\\bar{p}_J$   <br>\n      Pr(not detected)                  & $\\pi_{K} = 1-\\sum_{j=1}^J \\pi_j$          <br>\n      \\hline\n    \\end{tabular}\n:::\n\n\n\n\n\n\n\n## Point transects, no covariates\n  \nAbundance\n  \n\n::: {.cell}\n\n```{.r .cell-code}\nB <- 100; Area <- pi*B^2/1e4   ## plot radius (B) and area in ha\nnSites <- 100; lambda1 <- 0.9  ## Expected value of density\nN3 <- rpois(n=nSites, lambda=lambda1*Area)\n```\n:::\n\n  \n  \nMultinomial cell probabilities\n  \n\n::: {.cell}\n\n```{.r .cell-code}\nJ <- 5                     # distance bins\nsigma <- 50                # scale parameter\nb <- seq(0, B, length=J+1) # distance break points\narea <- pi*b^2             # area of each circle\npsi <- (area[-1]-area[-(J+1)]) / area[J+1]\npbar3 <- numeric(J)        # average detection probability\npi3 <- numeric(J+1)        # multinomial cell probs\nfor(j in 1:J) {\n    pbar3[j] <- integrate(function(x) exp(-x^2/(2*sigma^2))*x,\n                          lower=b[j], upper=b[j+1])$value *\n                          (2*pi/diff(area)[j])\n    pi3[j] <- pbar3[j]*psi[j] }; pi3[J+1] <- 1-sum(pi3[1:J])\n```\n:::\n\n  \n  \nDetections in each distance interval\n  \n\n::: {.cell}\n\n```{.r .cell-code}\ny3.all <- matrix(NA, nrow=nSites, ncol=J+1)\nfor(i in 1:nSites) {\n    y3.all[i,] <- rmultinom(n=1, size=N3[i], prob=pi3)    }\ny3 <- y3.all[,1:J]  ## Drop final cell\n```\n:::\n\n\n\n\n\n\n## Observed distances\n  \n\n::: {.cell}\n\n```{.r .cell-code}\nplot(b[-(J+1)]+10, colSums(y3), type=\"h\", lwd=80, lend=2, col=\"skyblue4\",\n     xlim=c(0,100), ylim=c(0, 70), xlab=\"Distance\", ylab=\"Detections\")\n```\n\n::: {.cell-output-display}\n![](lecture-distsamp-HDS_files/figure-revealjs/dist-hist3-1.png){width=90%}\n:::\n:::\n\n\n\n\n\n\n\n## Point transects, covariates\n  \nAbundance\n  \n\n::: {.cell}\n\n```{.r .cell-code}\nelevation <- rnorm(nSites)  \nbeta0 <- 2; beta1 <- 1\nlambda4 <- exp(beta0 + beta1*elevation)   # E(density)\nN4 <- rpois(n=nSites, lambda=lambda4*Area)\n```\n:::\n\n  \n  \nMultinomial cell probabilities\n  \n\n::: {.cell}\n\n```{.r .cell-code}\nnoise <- rnorm(nSites)\nalpha0 <- 3; alpha1 <- -0.5\nsigma4 <- exp(alpha0 + alpha1*noise)\npi4 <- matrix(NA, nSites, J+1) # multinomial cell probs\nfor(i in 1:nSites) {\n  for(j in 1:J) {\n      pi4[i,j] <- integrate(function(x) exp(-x^2/(2*sigma4[i]^2))*x,\n          lower=b[j], upper=b[j+1])$value*(2*pi/diff(area)[j])*psi[j] }\n  pi4[i,J+1] <- 1-sum(pi4[i,1:J]) } \n```\n:::\n\n  \n  \nDetections in each distance interval\n  \n\n::: {.cell}\n\n```{.r .cell-code}\ny4.all <- matrix(NA, nrow=nSites, ncol=J+1)\nfor(i in 1:nSites) {\n    y4.all[i,] <- rmultinom(n=1, size=N4[i], prob=pi4[i,])    }\ny4 <- y4.all[,1:J]\n```\n:::\n\n\n\n\n## Simulated data\n\n::: {.columns}\n::: {.column width='50%'}\n      \nObservations\n\n  \n\n::: {.cell}\n\n```{.r .cell-code}\ny4[1:25,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      [,1] [,2] [,3] [,4] [,5]\n [1,]    0    0    0    0    0\n [2,]    1    5    1    0    0\n [3,]    0    0    0    0    0\n [4,]    0    1    1    1    0\n [5,]    1    0    0    0    0\n [6,]    0    1    2    2    5\n [7,]    0    0    1    0    0\n [8,]    5    5    0    0    0\n [9,]    4    2    2    0    0\n[10,]    1    1    0    0    0\n[11,]    2    0    1    0    0\n[12,]    0    0    0    0    0\n[13,]    3    0    0    0    0\n[14,]    2    1    0    0    0\n[15,]    0    1    0    0    1\n[16,]    2    0    0    0    0\n[17,]    0    0    0    0    0\n[18,]    1    1    0    0    0\n[19,]    0    1    0    0    0\n[20,]    1    2    0    0    0\n[21,]    1    0    3    2    2\n[22,]    0    0    0    0    0\n[23,]    0    1    0    0    0\n[24,]    0    0    0    0    0\n[25,]    0    0    0    0    0\n```\n\n\n:::\n:::\n\n:::\n::: {.column width='50%'}\n    \nSummary stats\n    \n    \n::: {style='font-size: 80%;'}\nProportion of sites known to be occupied\n    \n\n::: {.cell}\n\n```{.r .cell-code}\n# Max count at each site\nmaxCounts <- apply(y4, 1, max) \nnaiveOccupancy <- sum(maxCounts>0)/nSites\nnaiveOccupancy \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.77\n```\n\n\n:::\n:::\n\n  \nTotal detections in each distance interval\n  \n\n::: {.cell}\n\n```{.r .cell-code}\ncolSums(y4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 89 99 54 35 30\n```\n\n\n:::\n:::\n\n  \n  \nNaive abundance\n  \n\n::: {.cell}\n\n```{.r .cell-code}\nsum(y4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 307\n```\n\n\n:::\n:::\n\n:::\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n## Prepare data in `unmarked'\n  \nNote the new arguments.\n  \n\n::: {.cell}\n\n```{.r .cell-code}\numf4 <- unmarkedFrameDS(y=y4, siteCovs=data.frame(elevation,noise), dist.breaks=b,\n                       survey=\"point\", unitsIn=\"m\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(umf4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nunmarkedFrameDS Object\n\npoint-transect survey design\nDistance class cutpoints (m):  0 20 40 60 80 100 \n\n100 sites\nMaximum number of distance classes per site: 5 \nMean number of distance classes per site: 5 \nSites with at least one detection: 77 \n\nTabulation of y observations:\n  0   1   2   3   4   5   6   7   8   9  10 \n351  85  31  13   6   5   2   2   1   2   2 \n\nSite-level covariates:\n   elevation           noise         \n Min.   :-2.2953   Min.   :-2.93845  \n 1st Qu.:-0.7225   1st Qu.:-0.72355  \n Median :-0.2411   Median :-0.06353  \n Mean   :-0.1119   Mean   :-0.05248  \n 3rd Qu.: 0.6033   3rd Qu.: 0.53973  \n Max.   : 2.2662   Max.   : 2.47751  \n```\n\n\n:::\n:::\n\n\n\n## Fit the model\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## fm4 <- distsamp(~noise ~elevation, umf4, keyfun=\"exp\")     # negative exp\n## fm4 <- distsamp(~noise ~elevation, umf4, keyfun=\"hazard\")  # hazard rate\nfm4 <- distsamp(~noise ~elevation, umf4, keyfun=\"halfnorm\")   # half-normal\nfm4\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\ndistsamp(formula = ~noise ~ elevation, data = umf4, keyfun = \"halfnorm\")\n\nDensity (log-scale):\n            Estimate     SE    z   P(>|z|)\n(Intercept)    2.003 0.0904 22.2 7.87e-109\nelevation      0.945 0.0662 14.3  3.29e-46\n\nDetection (log-scale):\n            Estimate     SE     z  P(>|z|)\n(Intercept)    2.963 0.0362  81.9 0.00e+00\nnoise         -0.525 0.0288 -18.2 5.75e-74\n\nAIC: 677.1907 \nNumber of sites: 100\n\nSurvey design: point-transect\nDetection function: halfnorm\nUnitsIn: m\nUnitsOut: ha \n```\n\n\n:::\n:::\n\n\n\n## Prediction in `unmarked'\n  \nCreate `data.frame` with prediction covariates. \n  \n\n::: {.cell}\n\n```{.r .cell-code}\npred.data <- data.frame(noise=seq(-3, 3, by=0.5))\n```\n:::\n\n\n\nGet predictions of $\\sigma$ for each row of prediction data.\n  \n\n::: {.cell}\n\n```{.r .cell-code}\nsigma.pred <- predict(fm4, newdata=pred.data,\n                      type='det', append=TRUE)\n```\n:::\n\n\n\nView $\\sigma$ predictions\n  \n\n::: {.cell}\n\n```{.r .cell-code}\nprint(head(sigma.pred), digits=2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Predicted   SE lower upper noise\n1        93 8.19    79   111  -3.0\n2        72 5.37    62    83  -2.5\n3        55 3.45    49    62  -2.0\n4        43 2.18    38    47  -1.5\n5        33 1.38    30    36  -1.0\n6        25 0.92    23    27  -0.5\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n## Prediction in `unmarked'\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(Predicted ~ noise, sigma.pred, ylab=\"Scale parameter (sigma)\",\n     ylim=c(0,100), xlab=\"Noise level\", type=\"l\")\nlines(lower ~ noise, sigma.pred, col=\"grey\")\nlines(upper ~ noise, sigma.pred, col=\"grey\")\n```\n\n::: {.cell-output-display}\n![](lecture-distsamp-HDS_files/figure-revealjs/pred-sigma-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n## Prediction in `unmarked'\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(Predicted ~ noise, sigma.pred, ylab=\"Scale parameter (sigma)\",\n     ylim=c(0,100), xlab=\"Noise level\", type=\"l\")\nlines(lower ~ noise, sigma.pred, col=\"grey\")\nlines(upper ~ noise, sigma.pred, col=\"grey\")\narrows(-2, sigma.pred$Predicted[3], 0.1, 63, len=0.1, col=\"blue\")\npoints(-2, sigma.pred$Predicted[3], col=\"orange\", pch=16, cex=2)\npar( fig=c(0.5,0.95,0.55,0.95), new=TRUE, las=1)#, mar=c(0,0,0,0) )\nplot(function(x) exp(-x^2/(2*40^2)), 0, 100, xlab=\"Dist\", ylab=\"p\",\n     col=\"orange\", lwd=2, ylim=c(0,1), las=1)\n```\n\n::: {.cell-output-display}\n![](lecture-distsamp-HDS_files/figure-revealjs/pred-sigma2-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n## Prediction in `unmarked'\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(Predicted ~ noise, sigma.pred, ylab=\"Scale parameter (sigma)\",\n     ylim=c(0,100), xlab=\"Noise level\", type=\"l\")\nlines(lower ~ noise, sigma.pred, col=\"grey\")\nlines(upper ~ noise, sigma.pred, col=\"grey\")\narrows(1, sigma.pred$Predicted[9], 1.1, 55, len=0.1, col=\"blue\")\npoints(1, sigma.pred$Predicted[9], col=\"red\", pch=16, cex=2)\npar( fig=c(0.5,0.95,0.55,0.95), new=TRUE, las=1)#, mar=c(0,0,0,0) )\nplot(function(x) exp(-x^2/(2*15^2)), 0, 100, xlab=\"Dist\", ylab=\"p\",\n     col=\"red\", lwd=2, ylim=c(0,1), las=1)\n```\n\n::: {.cell-output-display}\n![](lecture-distsamp-HDS_files/figure-revealjs/pred-sigma2-2-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n##  Conditional-on-*N* and *n_i*\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nmodel {\n\n# lambda.intercept ~ dunif(0, 20)\n# beta0 <- log(lambda.intercept)\nbeta0 ~ dnorm(0, 0.1)\nbeta1 ~ dnorm(0, 0.1)\n\nalpha0 ~ dnorm(0, 0.1)\nalpha1 ~ dnorm(0, 0.1)\n\nfor(i in 1:nSites) {\n  log(lambda[i]) <- beta0 + beta1*elevation[i]\n  N[i] ~ dpois(lambda[i]*Area)         # Latent local abundance\n  log(sigma[i]) <- alpha0 + alpha1*noise[i]\n  for(j in 1:nBins) {\n    ## Trick to do integration for *point-transects*\n    pbar[i,j] <- (sigma[i]^2 * (1-exp(-b[j+1]^2/(2*sigma[i]^2))) -\n                  sigma[i]^2 * (1-exp(-b[j]^2/(2*sigma[i]^2)))) * \n                 2*3.141593/area[j]     \n    pi[i,j] <- psi[j]*pbar[i,j]         ## Pr(present and detected in bin j)\n  }\n  pi[i,nBins+1] <- 1-sum(pi[i,1:nBins]) ## Pr(not detected)\n  n[i] ~ dbin(1-pi[i,nBins+1], N[i])\n  y[i,] ~ dmulti(pi[i,1:nBins]/(1-pi[i,nBins+1]), n[i])\n  ## If N~Pois(lam), then the above is equivalent to:\n  # for(j in 1:nBins) { y[i,j] ~ dpois(lambda[i]*pi[i,j])  }\n}\n\ntotalAbundance <- sum(N[1:nSites])\n\n}\n```\n\n\n:::\n:::\n\n\n\n\n## Data, inits, and parameters\n\nPut data in a named list\n  \n\n::: {.cell}\n\n```{.r .cell-code}\njags.data.pt <- list(y=y4, n=rowSums(y4), area=diff(area),\n                     b=b,              # Distance break points\n                     Area=pi*B^2/1e4,  # Area in ha\n                     psi=psi,          # Pr(occuring in bin j)\n                     elevation=elevation, noise=noise,\n                     nSites=nSites, nBins=J)\n```\n:::\n\n\nInitial values\n  \n\n::: {.cell}\n\n```{.r .cell-code}\njags.inits.pt <- function() {\n    list(beta0=rnorm(1), alpha0=rnorm(1, 5),\n         N=rowSums(y4)+rpois(nrow(y4), 2))\n}\n```\n:::\n\n\nParameters to monitor\n  \n\n::: {.cell}\n\n```{.r .cell-code}\njags.pars.pt <- c(\"beta0\", \"beta1\",\n                  \"alpha0\", \"alpha1\", \"totalAbundance\")\n```\n:::\n\n\n\n\n## MCMC\n  \n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(jagsUI)\njags.post.pt <- jags.basic(data=jags.data.pt, inits=jags.inits.pt,\n                           parameters.to.save=jags.pars.pt,\n                           model.file=\"distsamp-point-mod.jag\",\n                           n.chains=3, n.adapt=100, n.burnin=0,\n                           n.iter=2000, parallel=TRUE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(summary(jags.post.pt)$quantile, digits=3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   2.5%      25%      50%      75%    97.5%\nalpha0            2.895    2.940    2.964    2.989    3.031\nalpha1           -0.587   -0.549   -0.529   -0.510   -0.474\nbeta0             1.806    1.922    1.985    2.050    2.158\nbeta1             0.833    0.914    0.958    1.008    1.108\ntotalAbundance 2847.000 3099.000 3264.500 3459.000 3814.025\n```\n\n\n:::\n:::\n\n\n\n# Line transects\n\n## [Multinomial cell probs for line transects]{style=\"font-size: 90%;\"}\n  \nDefinitions needed for computing \\alert{bin-specific} $\\bar{p}$ and multinomial cell probabilities. \n  \n    * $y_{ij}$ -- number of individuals detected at site $i$ in bin $j$\n    * $\\sigma_i$ -- scale parameter of detection function $g(x)$\n    * $b_1, \\dots, b_{J+1}$ -- Distance break points defining $J$ distance intervals\n    * $\\bar{p}_j$ -- Average detection probability in distance bin j\n    * $\\psi_j$ -- Pr(occuring in distance bin $j$)\n  \n<!-- ::: columns -->\n<!--     \\column{0.9\\paperwidth} -->\n<!--     \\begin{tabular}{lc} -->\n<!--       \\hline -->\n      \n<!--       Description                       & Multinomial cell probability <br> -->\n<!--       \\hline -->\n<!--       Pr(occurs and detected in first distance bin)  & $\\pi_1 = \\psi_1\\bar{p}_1$   <br> -->\n<!--       Pr(occurs and detected in second distance bin)  & $\\pi_2 = \\psi_2\\bar{p}_2$   <br> -->\n<!--       { $\\cdots$}             & $\\cdots$                     <br> -->\n<!--       Pr(occurs and detected in last distance bin)  & $\\pi_J = \\psi_J\\bar{p}_J$   <br> -->\n<!--       Pr(not detected)                  & $\\pi_{K} = 1-\\sum_{j=1}^J \\pi_j$          <br> -->\n<!--       \\hline -->\n<!--     \\end{tabular} -->\n<!-- ::: -->\n\n\n\n\n\n\n\n\n## Line transects, no covariates\n  \nAbundance\n  \n\n::: {.cell}\n\n```{.r .cell-code}\nB <- 100; L <- 100; A <- 2*B*L/1e4  ## transect widths, length, and area\nnSites <- 100; lambda1 <- 1.3       ## Expected value of density\nN1 <- rpois(n=nSites, lambda=lambda1*A)\n```\n:::\n\n  \n  \nMultinomial cell probabilities\n  \n\n::: {.cell}\n\n```{.r .cell-code}\nJ <- 5                     # distance bins\nsigma <- 50                # scale parameter\nb <- seq(0, B, length=J+1) # distance break points\npsi <- diff(b)/B           # Pr(x is in bin j)\npbar1 <- numeric(J)        # average detection probability\npi1 <- numeric(J+1)        # multinomial cell probs\nfor(j in 1:J) {\n    pbar1[j] <- integrate(function(x) exp(-x^2/(2*sigma^2)),\n                          lower=b[j], upper=b[j+1])$value / diff(b)[j]\n    pi1[j] <- pbar1[j]*psi[j]\n}\npi1[J+1] <- 1-sum(pi1[1:J])\n```\n:::\n\n  \n  \nDetections in each distance interval\n  \n\n::: {.cell}\n\n```{.r .cell-code}\ny1.all <- matrix(NA, nrow=nSites, ncol=J+1)\nfor(i in 1:nSites) {\n    y1.all[i,] <- rmultinom(n=1, size=N1[i], prob=pi1)    }\ny1 <- y1.all[,1:J]  ## Drop final cell\n```\n:::\n\n\n\n## Observed distances\n  \n\n::: {.cell}\n\n```{.r .cell-code}\nplot(b[-(J+1)]+10, colSums(y1), type=\"h\", lwd=80, lend=2, col=\"skyblue4\",\n     xlim=c(0,100), ylim=c(0, 70), xlab=\"Distance\", ylab=\"Detections\")\n```\n\n::: {.cell-output-display}\n![](lecture-distsamp-HDS_files/figure-revealjs/dist-hist2-1.png){width=90%}\n:::\n:::\n\n\n\n\n\n\n\n## Line transects, covariates\n  \n::: {style='font-size: 70%;'}\nAbundance\n  \n\n::: {.cell}\n\n```{.r .cell-code}\nelevation <- rnorm(nSites)  \nbeta0 <- 2; beta1 <- 1\nlambda2 <- exp(beta0 + beta1*elevation)\nN2 <- rpois(n=nSites, lambda=lambda2*A)\n```\n:::\n\n  \n  \nMultinomial cell probabilities\n  \n\n::: {.cell}\n\n```{.r .cell-code}\nnoise <- rnorm(nSites)\nalpha0 <- 3; alpha1 <- -0.5\nsigma2 <- exp(alpha0 + alpha1*noise)\npi2 <- matrix(NA, nSites, J+1) # multinomial cell probs\nfor(i in 1:nSites) {\n  for(j in 1:J) {\n      pi2[i,j] <- integrate(function(x) exp(-x^2/(2*sigma2[i]^2)),\n          lower=b[j], upper=b[j+1])$value / (b[j+1]-b[j]) * psi[j] }\n  pi2[i,J+1] <- 1-sum(pi2[i,1:J]) } \n```\n:::\n\n  \n  \nDetections in each distance interval\n  \n\n::: {.cell}\n\n```{.r .cell-code}\ny2.all <- matrix(NA, nrow=nSites, ncol=J+1)\nfor(i in 1:nSites) {\n    y2.all[i,] <- rmultinom(n=1, size=N2[i], prob=pi2[i,])    }\ny2 <- y2.all[,1:J]\n```\n:::\n\n\n:::\n\n\n\n## Simulated data\n\n::: {.columns}\n\n::: {.column width='50%'}\n      \nObservations\n  \n\n::: {.cell}\n\n```{.r .cell-code}\ny2[1:25,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      [,1] [,2] [,3] [,4] [,5]\n [1,]    3    2    0    0    0\n [2,]    4    1    1    0    0\n [3,]    6    2    3    0    0\n [4,]    7    4    1    0    0\n [5,]    2    2    0    0    0\n [6,]    0    0    0    0    0\n [7,]    1    0    0    0    0\n [8,]    5    0    1    0    0\n [9,]    3    7    2    0    0\n[10,]    5    2    0    0    0\n[11,]    4    2    0    0    0\n[12,]    5    2    0    0    0\n[13,]    2    1    0    0    0\n[14,]   12   10    8    4    1\n[15,]    3    0    0    0    0\n[16,]    3    0    0    0    0\n[17,]    2    0    0    0    0\n[18,]    9    1    0    0    0\n[19,]    7    5    4    0    0\n[20,]    1    1    1    0    0\n[21,]    5    4    2    1    0\n[22,]    1    1    1    3    0\n[23,]    3    2    0    0    0\n[24,]    1    0    1    0    0\n[25,]    7    8    4    1    2\n```\n\n\n:::\n:::\n\n:::\n::: {.column width='50%'}\n    \nSummary stats\n    \n    \nProportion of sites known to be occupied\n    \n\n::: {.cell}\n\n```{.r .cell-code}\n# Max count at each site\nmaxCounts <- apply(y2, 1, max) \nnaiveOccupancy <- sum(maxCounts>0)/nSites\nnaiveOccupancy \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9\n```\n\n\n:::\n:::\n\n\nTotal detections in each distance interval\n  \n\n::: {.cell}\n\n```{.r .cell-code}\ncolSums(y2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 360 151  63  32  15\n```\n\n\n:::\n:::\n\n  \nNaive abundance\n  \n\n::: {.cell}\n\n```{.r .cell-code}\nsum(y2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 621\n```\n\n\n:::\n:::\n\n:::\n:::\n\n\n\n\n\n\n\n## Prepare data in 'unmarked'\n  \nNote the new arguments.\n  \n\n::: {.cell}\n\n```{.r .cell-code}\numf <- unmarkedFrameDS(y=y2, siteCovs=data.frame(elevation,noise), dist.breaks=b,\n                       tlength=rep(L, nSites), survey=\"line\", unitsIn=\"m\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(umf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nunmarkedFrameDS Object\n\nline-transect survey design\nDistance class cutpoints (m):  0 20 40 60 80 100 \n\n100 sites\nMaximum number of distance classes per site: 5 \nMean number of distance classes per site: 5 \nSites with at least one detection: 90 \n\nTabulation of y observations:\n  0   1   2   3   4   5   6   7   8   9  10  11  12  15  17  19  28 \n308  75  39  25  12  10   6   8   6   2   2   1   1   2   1   1   1 \n\nSite-level covariates:\n   elevation            noise         \n Min.   :-2.15115   Min.   :-2.80421  \n 1st Qu.:-0.67921   1st Qu.:-0.83893  \n Median :-0.20250   Median :-0.06718  \n Mean   :-0.07937   Mean   :-0.18973  \n 3rd Qu.: 0.60327   3rd Qu.: 0.39358  \n Max.   : 2.03949   Max.   : 1.84018  \n```\n\n\n:::\n:::\n\n\n\n## Fit the model\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## fm <- distsamp(~noise ~elevation, umf, keyfun=\"exp\")     # negative exp\n## fm <- distsamp(~noise ~elevation, umf, keyfun=\"hazard\")  # hazard rate\nfm <- distsamp(~noise ~elevation, umf, keyfun=\"halfnorm\")   # half-normal\nfm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\ndistsamp(formula = ~noise ~ elevation, data = umf, keyfun = \"halfnorm\")\n\nDensity (log-scale):\n            Estimate     SE    z   P(>|z|)\n(Intercept)     2.05 0.0611 33.5 2.00e-245\nelevation       1.02 0.0489 21.0  1.82e-97\n\nDetection (log-scale):\n            Estimate     SE     z  P(>|z|)\n(Intercept)    2.929 0.0369  79.4 0.00e+00\nnoise         -0.513 0.0312 -16.5 5.68e-61\n\nAIC: 824.6483 \nNumber of sites: 100\n\nSurvey design: line-transect\nDetection function: halfnorm\nUnitsIn: m\nUnitsOut: ha \n```\n\n\n:::\n:::\n\n\n\nCompare to actual parameter values:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(beta0=beta0, beta1=beta1); c(alpha0=alpha0, alpha1=alpha1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nbeta0 beta1 \n    2     1 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nalpha0 alpha1 \n   3.0   -0.5 \n```\n\n\n:::\n:::\n\n\n##  Conditional-on-*N* and *n~i~*\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nmodel {\n\nbeta0 ~ dnorm(0, 0.1)\nbeta1 ~ dnorm(0, 0.1)\n\nalpha0 ~ dnorm(0, 0.1)\nalpha1 ~ dnorm(0, 0.1)\n\nfor(i in 1:nSites) {\n  log(lambda[i]) <- beta0 + beta1*elevation[i]\n  N[i] ~ dpois(lambda[i]*Area)         # Latent local abundance\n  log(sigma[i]) <- alpha0 + alpha1*noise[i]\n  tau[i] <- 1/sigma[i]^2\n  for(j in 1:nBins) {\n    ## Trick to do integration for *line-transects*\n    pbar[i,j] <- (pnorm(b[j+1], 0, tau[i]) - pnorm(b[j], 0, tau[i])) /\n                  dnorm(0, 0, tau[i]) / (b[j+1]-b[j])\n    pi[i,j] <- psi[j]*pbar[i,j]         ## Pr(present and detected in bin j)\n  }\n  pi[i,nBins+1] <- 1-sum(pi[i,1:nBins]) ## Pr(not detected)\n  n[i] ~ dbin(1-pi[i,nBins+1], N[i])\n  y[i,] ~ dmulti(pi[i,1:nBins]/(1-pi[i,nBins+1]), n[i])\n  ## If N~Pois(lam), then the above is equivalent to:\n  # for(j in 1:nBins) { y[i,j] ~ dpois(lambda[i]*pi[i,j])  }\n}\n\ntotalAbundance <- sum(N[1:nSites])\n\n}\n```\n\n\n:::\n:::\n\n\n## Data, inits, and parameters\n\nPut data in a named list\n  \n\n::: {.cell}\n\n```{.r .cell-code}\njags.data.line <- list(y=y2, n=rowSums(y2),\n                       b=b,           # Distance break points\n                       psi=diff(b)/B, # Pr(occuring in bin j)\n                       Area=A,        # Area in ha\n                       elevation=elevation, noise=noise,\n                       nSites=nSites, nBins=J)\n```\n:::\n\n\n\nInitial values\n  \n\n::: {.cell}\n\n```{.r .cell-code}\njags.inits.line <- function() {\n    list(beta0=rnorm(1), alpha0=rnorm(1, 5),\n         N=rowSums(y2)+rpois(nrow(y2), 2))\n}\n```\n:::\n\n\n\nParameters to monitor\n  \n\n::: {.cell}\n\n```{.r .cell-code}\njags.pars.line <- c(\"beta0\", \"beta1\",\n                    \"alpha0\", \"alpha1\", \"totalAbundance\")\n```\n:::\n\n\n\n\n## MCMC\n  \n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(jagsUI)\njags.post.line <- jags.basic(data=jags.data.line, inits=jags.inits.line,\n                             parameters.to.save=jags.pars.line,\n                             model.file=\"distsamp-line-mod.jag\",\n                             n.chains=3, n.adapt=100, n.burnin=0,\n                             n.iter=2000, parallel=TRUE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(summary(jags.post.line)$quantile, digits=3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   2.5%      25%      50%      75%    97.5%\nalpha0            2.857    2.905    2.928    2.952    3.003\nalpha1           -0.578   -0.536   -0.515   -0.494   -0.458\nbeta0             1.915    2.004    2.046    2.085    2.161\nbeta1             0.930    0.990    1.022    1.055    1.119\ntotalAbundance 1921.975 2045.000 2112.000 2181.000 2314.025\n```\n\n\n:::\n:::\n\n\n\n\n\n## Traceplots and density plots\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(jags.post.line[,jags.pars.line[1:3]])\n```\n\n::: {.cell-output-display}\n![](lecture-distsamp-HDS_files/figure-revealjs/bugs-plot1-rem2-1.png){fig-align='center' width=0.7<br>textwidth}\n:::\n:::\n\n\n\n\n## Traceplots and density plots\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(jags.post.line[,jags.pars.line[4:5]])\n```\n\n::: {.cell-output-display}\n![](lecture-distsamp-HDS_files/figure-revealjs/bugs-plot2-rem2-1.png){fig-align='center' width=0.7<br>textwidth}\n:::\n:::\n\n\n\n\n\n# Summary\n\n\n\n## Distance sampling summary\n\nAssumptions\n  \n- Animals don't move during the survey\n- Animals are uniformly distributed with respect to the transects\n- Detection is certain on the transect, i.e. $p=1$ when $x=0$. \n- Detections are independent\n\nIf these assumptions can be met, distance sampling is a powerful method allowing for inference about abundance and density using data from a single visit.\n\n\n\n\n# Assignment\n\n\n## Assignment\n\n::: {style='font-size: 80%;'}\nCreate a self-contained R script or Rmarkdown file to do the following:\n  \n- Fit a distance sampling model with a half-normal detection\n     function and the following covariates to the black-throated blue\n      warbler data ({\\tt btbw\\_data\\_distsamp.csv}) in `unmarked' and\n      `JAGS':\n      \n  * Density covariates: `Elevation, UTM.N, UTM.W`\n  * Detection covariates: `Wind, Noise`\n  * Response: `btbw0\\_20, btbw20\\_40, btbw40\\_60, btbw60\\_80, btbw80\\_100`\n      \n- Using the model fitted in `unmarked', create two graphs of\n  the predictions: one for density and the other for the scale\n  parameter ($\\sigma$).\n  \nSuggestions:\n  \n- Convert response variables to matrix with \\inr{as.matrix}\n- Standardize covariates\n  \n\n  Upload your `.R` or `.Rmd` file to ELC by 5:00pm on Tuesday. \n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}